examples/aes/Cargo.toml
examples/aes128-gcm/Cargo.toml
examples/chacha20/Cargo.toml
examples/chacha20poly1305/Cargo.toml
examples/curve25519/Cargo.toml
examples/ecdsa-p256-sha256/Cargo.toml
examples/ed25519/Cargo.toml
examples/gf128/Cargo.toml
examples/gimli/Cargo.toml
examples/p256/Cargo.toml
examples/poly1305/Cargo.toml

Switch the local path for `hacspec-dev` to a git dependency and propagate it to examples that need it

Fix cargo toml deps

---

engine/lib/import_thir.ml

This PR just adds a bit of information on the errors that `import_thir` yields, so that thir_import.ml related errors are more than just `Unimplemented {details: None}`.

`import_thir`: add details to some diagnostics

---

frontend/exporter/src/items.rs
test-harness/src/harness.rs
tests/enum-struct-variant/Cargo.toml

We want to skip derived implementations for `PartialEq`, `Eq`, `Clone`, `Debug`. This patch filters out every item that was automatically derived. This is a too coarse filter, we need to rework that.

Temporary fix for `derive`d code (fixes #78)

---

setup.sh

This PR adds `--force` flag by default to `setup.sh` so that people can update Hax properly.
Otherwise, `cargo install` sees a binary with the same name, and skips the installation.

Add `--force` flag to `cargo install`

---

.github/workflows/install_and_test.yml
cli/options/src/lib.rs
engine/backends/coq/coq_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/import_thir.ml
engine/utils/hacspeclib-macro-parser/hacspeclib_macro_parser.ml

Small fixes after #98, notably, update the list of examples that are still failing, so that the CI and #28 reflect the same thing.
Now, only two v1 examples are not extracting: `tls_cryptolib` and `hacspec-merlin`.

Small fixes

---

engine/DEV.md
engine/lib/diagnostics.ml
engine/lib/phase_utils.ml
engine/lib/print_rust.ml
engine/lib/print_rust.mli
engine/lib/utils.ml
engine/utils/phase_debug_webapp/script.js

Fixes `--debug-engine` `EMFILE` issues, and optimize a bit perfs.
More specifically:
- I was not closing processes correctly in OCaml while `rustfmt` items;
- (in debug mode) now I run one `rustfmt` for each phase, before the engine was running `n` `rustfmt`s for each phase, with `n` the number of items.

Fix performance and process limit issue with `--debug-engine`

---

frontend/exporter/src/all.rs
tests/generics/src/lib.rs

Fixes the construction of arrays `[x; LEN]` when `LEN` is not a literal.

Remove specific code for `[x; LEN]`, use general const to expr

---

cli/driver/src/exporter.rs
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/diagnostics.ml
engine/lib/feature_gate.ml
engine/lib/phase_utils.ml
engine/lib/print_rust.ml
engine/utils/hacspeclib-macro-parser/hacspeclib_macro_parser.ml
frontend/exporter/src/all.rs
frontend/exporter/src/items.rs

I found some other code that triggers the steal error.
This PR makes the error recoverable using some unsafe things: we report an error but keep going.

Make `Steal` error recoverable, make more errors non-fatal

---

.github/workflows/install_and_test.yml
engine/lib/import_thir.ml

Those are not supported yet, PR #149 and #160 will fix those.
But for now, that blocks all the PRs, so we should disable those.

Disable `halo2` and `weierstrass` in the tests of Hax

---

engine/lib/import_thir.ml
frontend/exporter/src/all.rs
tests/Cargo.lock
tests/Cargo.toml
tests/enum-repr/Cargo.toml
tests/enum-repr/src/lib.rs

This PR transforms `NonHirLiteral`s into "normal" literals in the frontend.
Thus, this removes NonHirLiteral from THIR' (the JSON one).

Frontend: transform `NonHirLiteral` into `Literal` (fixes #162)

---

.github/workflows/format.yml
.github/workflows/install_and_test.yml
.github/workflows/release.yml

Simplifies a bit the CI & should improve performances.
This replaces [Cachix](https://app.cachix.org/cache/hacspec) with https://github.com/DeterminateSystems/magic-nix-cache, that uses Github Actions cache.
That's less configuration and fetching cache should be faster.

Switch from `cachix` to `DeterminateSystems/magic-nix-cache`

---

engine/lib/ast_utils.ml
tests/nested-derefs/Cargo.toml
tests/nested-derefs/src/lib.rs

Expressions are now un`box`ed and un`deref`ed as much as possible instead of only once.
**Merge me after #172**

Fix `unbox_expr` and `underef_expr` when nested box/deref exprs

---

cli/driver/src/exporter.rs
cli/options/engine/src/lib.rs
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/diagnostics.ml
engine/lib/import_thir.ml
engine/lib/print_rust.ml
engine/lib/span.ml
engine/lib/span.mli
engine/utils/phase_debug_webapp/script.js
frontend/diagnostics/src/lib.rs
tests/nested-derefs/Cargo.toml
tests/nested-derefs/src/lib.rs

- Error messages were not reporting their context (at which phase the error was raised)
- `CE00XX` was standing for circus error, renamed that into `HAX00XX`

Improve a bit error messages & codes

---

.github/workflows/test_installs.yml

anything else but merge groups.
The idea comes from https://github.com/bevyengine/bevy/issues/7824#issuecomment-1562380615.

Explicitly disable the (required) jobs `docker` and `setup_sh` for

---

.github/workflows/test_installs.yml

We need `setup_sh (OS)` with `OS` being `ubuntu-latest`, `ubuntu-20.04` , `macos-latest` or `macos-11` to be required jobs.
But we need to skip those jobs in PRs, so that they are triggered only when in merge queue. This is done with an `if`, but it operates only on jobs, not on matrix instances, so we cannot disable `setup_sh (OS)`, only `setup_sh` itself.
Then:
- if we set `setup_sh (OS)` as required jobs, that's not fine since only `setup_sh` is reported as skipped (`setup_sh (OS)` don't get reported at all);
- if we set `setup_sh` as a required job, then, we're able to push PRs to the merge queue, but once it's in the merge queue, GH doesn't create a `setup_sh` at all, only `setyp_sh (OS)`.
Whence this solution: a `setup_sh_status` job that aggregates the status of our 4 `setup_sh …

Add a `setup_sh_status` job

---

engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast_utils.ml

This utils adds type ascription nodes in nested function calls. This helps type inference in the presence of associated types in backends that don't support them well (F* for instance).
Examples:
- `f (g x)` is turned into `f (g x <: τ)`;
- `f (let x = g x in x)` is left unchanged (the F* backend annotates `let` already);
- `f x + g x` is turned into `(f x <: τ₁) + (g x <: τ₂)`;
- `f (g x <: τ)` is left unchanged (`g x` already has a type ascription).
(edit: there is no test for this since; that's backend-specific and it's noticeable only while F* typechecking)

Add `Ast_utils.add_typ_ascription`

---

.utils/rebuild.sh
README.md
flake.nix

Adds a `rebuild.sh` script (in a new `.utils` folder) that compiles the different parts Hax in dev mode in the right order from wherever in the repo.

Add `rebuild` script for development

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/easycrypt/easycrypt_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/concrete_ident/names.rs
engine/lib/import_thir.ml
engine/lib/phases/phase_cf_into_monads.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_local_mutation.ml
engine/lib/phases/phase_reconstruct_for_loops.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
tests/Cargo.lock
tests/Cargo.toml
tests/never-type/Cargo.toml
tests/never-type/src/lib.rs

With the never type (noted `!` in Rust), it's possible to match against empty enums. The engine used to assume a match had at least one arm. Now, we pick the first arm not typed `!`, and resort to `!` if no such arm exists.
Status: this PR introduces some TFalse nodes, which are not supported by Coq, gotta fix that

Accept zero-arm matches, insert `never_to_any` coercition 

---

engine/lib/concrete_ident/generate.sh
setup.sh

This PR:
- refactors `setup.sh`;
- adds checks for system dependencies (currently: node, rustup, opam, jq);
- adds env var `OPAMERRLOGLEN` so that `opam` display error logs when an error occurs (otherwise users are facing useless error messages, for them as well as for us);
- adds env var `OCAMLRUNPARAM` and `OPAMJOBS` to limit the amount of memory used, fixing #197.
Note regarding #197: other people are facing high memory consumption while compiling OCaml stuff, see https://discuss.ocaml.org/t/how-to-limit-the-amount-of-memory-the-ocaml-compiler-is-allowed-to-use/797/2.

Improve setup and dependencies

---

frontend/exporter/src/types/copied.rs

@franziskuskiefer found the following bug:
```rust
pub const MY_VAL: u16 = 5;
pub type Alias = MyStruct<MY_VAL>; // Using the literal 5, it goes through
pub struct MyStruct<const VAL: u16> {}
impl<const VAL: u16> MyStruct<VAL> {
pub const MY_CONST: u16 = VAL;
}
pub fn do_something() -> u32 {
u32::from(Alias::MY_CONST)
}
```
The `Alias::MY_CONST` in `do_something` yields a `UserTy` node in the translated AST, which contains a Debruijn index, that we don't handle properly. Since we never use `UserTy`, this PR just disable its translation, thus fixing the issue.

Exporter: disable the translation of `UserTy` for now

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
engine/lib/utils.ml
frontend/exporter/src/types/copied.rs
tests/Cargo.lock
tests/Cargo.toml
tests/attributes/Cargo.toml
tests/attributes/README.md
tests/attributes/src/lib.rs

This PR:
- transports all the Rust item attributes;
- improve the debug Rust printer (it now prints those attributes, and also enum/structs).
The attributes can be on:
- generic parameters;
- function parameters;
- variants;
- variant fields;
- items themselves.

Engine: reflect attributes on items

---

Cargo.lock
cli/driver/Cargo.toml
cli/driver/src/exporter.rs
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/types/copied.rs

This PR fixes a few things:
- more `steal`ing issues (but not all, I found some, one in `Core`, notably);
- misc. bugs with char consts, opaque types and generic bounds;
- we now translate correctly `PhantomData`s.
Those fixes are for bugs I stumbled upon while looking at big crate (`Core`, but not only), thus that's generally pretty hard to minimize. (that's why this PR doesn't ship unit tests)

Exporter: misc. improvements

---

frontend/exporter/src/types/copied.rs

I discarded this change from PR #200 while refactoring the frontend, reapplying.
Fixing issue #227.

Reapply: Trait items bounds: fix & use item_bounds when necessary

---

cli/options/src/lib.rs
engine/bin/lib.ml
engine/lib/concrete_ident/concrete_ident.ml
engine/lib/concrete_ident/concrete_ident.mli
engine/lib/import_thir.ml
engine/lib/import_thir.mli

Consider the following crate:
```rust
fn f() {}
mod hello {
fn g() {}
const _: () = {
fn h() {}
fn i() {}
}
}
fn j() {}
```
This PR allows for things like: `cargo hax into -i '-** +f +hello::** -hello::*::h'`, which results in extracting `f`, `g`, `i`, but not `h` or `j`.

CLI: allow for including/excluding items from the translation

---

engine/lib/concrete_ident/generate.sh

We've spend time with @R1kM trying to debug `generate.sh` while actually everything was fine with the script itself, the faulty thing was the shell it was run with.
Whence that PR, so that we don't hit the same thing again in the future

Add a missing shebang on `generate.sh`

---

cli/driver/src/exporter.rs
cli/options/engine/src/lib.rs
cli/options/src/lib.rs
cli/subcommands/build.rs
cli/subcommands/src/cargo_hax.rs
engine/lib/concrete_ident/generate.sh

Since #234 we are now able to extract directly in the frontend a list of definition identifiers.
Thus, this makes a part of the `generate.sh` script useless; the PR drop that useless part and simplifies the rest.
This should also help make the script more cross-platform: we recently had error reports (from @R1kM and @xvzcf notably), and I suspect those were due to `base64` behaving in a strange way on MacOS (now the generate.sh script doesn't use that anylonger).

Rewrite `generate.sh` script

---

.utils/rebuild.sh

This PR improves the `./.utils/rebuild.sh` script:
- add `<TASK> build started` logs;
- add sanity checks, emit warning when, after `dune install`:
+ `hax-engine` is not in `PATH`;
+ `hax-engine` is more than once in `PATH` (happened to @R1kM, causing absolutely incomprehensible errors!).

Improve `rebuild.sh` script

---

engine/bin/dune
engine/bin/js_driver.ml
engine/bin/lib.ml
engine/bin/lib.mli
engine/bin/native_driver.ml
engine/default.nix
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js

First half of #261:
- Add a few missing features to the JSON schema to OCaml script;
- Use native JS JSON parser while compiling the engine with JS.

Revive js engine

---

engine/lib/ast.ml
engine/utils/ppx_generate_features/ppx_generate_features.ml

This adds PPX attributes so that every type involved in the functorized AST implement `hash`.

feat(engine/ast): derive `hash` systematically

---

engine/lib/import_thir.ml

This PR changes the kind of impl identifiers in impl expressions.
(the name of an impl `foo` was outputted as `t_foo` instead of `i_foo`)

fix(engine/import-thir): fix kind of impl ids

---

cli/driver/src/exporter.rs

Currently, the driver keeps going and lets Rustc compile all the way to binary production.
That's not what we want, since doing that triggers the borrow checker: for annotations we really don't want the borrow checker to run.

fix(driver): stop rustc compilation after running Hax

---

engine/lib/ast_utils.ml
engine/lib/phases/phase_and_mut_defsite.ml
tests/mut-ref-functionalization/src/lib.rs

In the expression `x[i] = e`, `x[i]` was handled correctly only if the underlying indexing operation was [IndexMut](https://doc.rust-lang.org/core/ops/trait.IndexMut.html#tymethod.index_mut).
However, if `x` is of type `&mut T`, the trait being used is not [IndexMut](https://doc.rust-lang.org/core/ops/trait.IndexMut.html#tymethod.index_mut) anylonger but [Index](https://doc.rust-lang.org/core/ops/trait.Index.html#tymethod.index)!
This PR basically adds support for Index `x[i]` in LHS of assigns. It also adds a test.

Fixes for &mut index assignations

---

hax-lib-macros/src/lib.rs
hax-lib-macros/src/rewrite_self.rs
hax-lib-macros/src/utils.rs

This PR makes the crate `hax-lib-macros` buildable with non-nightly Rustc

fix(hax-lib-macros): drop nightly features

---

frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/state.rs
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap

This is important otherwise we get extra `T: Trait` constraints when implementing `T` for `Trait`.

fix(frontend): use `predicates_defined_on` instead of `predicate_of`

---

engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/phases/phase_and_mut_defsite.ml
engine/lib/phases/phase_direct_and_mut.ml
engine/lib/phases/phase_trivialize_assign_lhs.ml
engine/lib/print_rust.ml
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
tests/mut-ref-functionalization/src/lib.rs

Fixes #256: `copy_from_slice` (and any other functions with &mut inputs actually) on sized things (e.g. fixed size arrays `[T; N]`) 
This is related to thin / fat pointers.
cc @karthikbhargavan @xvzcf @geonnave

Fix unsizes on mutations

---

engine/dune-project
engine/hax-engine.opam

Does that fix the bug of missing `js_of_ocaml` while building the engine @franziskuskiefer?

fix(engine): add all `js_of_ocaml` dependencies

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap

Before, closures used to be translated to untyped lambdas in F*, now they are translated to typed lambdas.
Example: `|x: u64| x + x` was `fun x -> x + x`, now it is `fun (x: u64) -> x + x`.

feat(fstar/engine): add types on closure binders

---

engine/lib/diagnostics.ml
engine/lib/generic_printer/generic_printer.ml
engine/lib/generic_printer/generic_printer.mli
engine/lib/generic_printer/generic_printer_base.ml

Start an exploration of a generic printer, aiming at factorizing backends a little.
In this PR the default printer is a Rust-like printer for the whole AST; the idea is to have a printer per family of languages.
For instance, Lean, Coq and F* share a lot in terms of structure.
This implementation uses OCaml classes (surprisingly!). This is somehow a bit nice here because we want to be able to refine an printer in another printer: we could have a `FunctionalFlavorPrinter` as a basis for `CoqPrinter`, `FStarPrinter` an d `LeanPrinter` that would override some parts of `FunctionalFlavorPrinter`, but inherit other parts.
In OCaml, I think OOP is the only way to achieve that. In type-class capable languages, we could use a double-dispatch thing with typeclasses and default implementation of …

Generic printer

---

engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/dependencies.mli
engine/lib/generic_printer/generic_printer.ml
engine/lib/generic_printer/generic_printer_base.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_direct_and_mut.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_reconstruct_for_loops.ml
engine/lib/phases/phase_recontruct_for_index_loops.ml
engine/lib/print_rust.ml
engine/lib/side_effect_utils.ml
engine/lib/subtype.ml
frontend/exporter/src/types/copied.rs
tests/generics/src/lib.rs

This is particularly important for generic constants: if a generic constant on a function is not constrained enough (in terms of type), and if we extract it as an implicit parameter, then the target language might not be able to infer it.
Thus, we need those const generics to be explicit.
This PR propagates the (until then implicit) information about generics (constants, but also types and lifetimes). 
Now, I need to either:
EDIT: tweaking the backends is the way to go, we cannot always convert const-generics to normal terms.

feat(engine): propagate generics in fun calls

---

engine/backends/fstar/fstar_backend.ml
examples/chacha20/proofs/fstar/extraction/Chacha20.Hacspec_helper.fst
examples/chacha20/proofs/fstar/extraction/Chacha20.diff
examples/chacha20/proofs/fstar/extraction/Chacha20.fst
examples/chacha20/src/lib.rs
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap

We used to have closure like `|x: T, y: U| body` extract to `fun (x:
T) (y: U) -> body` in the F* backend.
When such a typed lambda is consumed by a higer-order function, we sometimes face issues with unification in F*.
This commit introduce a trick that allows for better unification in F*: we now generate a let binding per input in lambdas. For example, `|x: T, y: U| body` now extracts to:
```fstar
fun x y ->
let x: T = x in
let y: T = y in
body
```

feat(engine/fstar): `let`s instead of typing lambdas

---

engine/backends/fstar/fstar_backend.ml
hax-lib-macros/src/lib.rs
tests/attributes/src/lib.rs

Before, users were able to write lemma *statements* (that would in turn translate to lemmas in the backends), not lemmas themselves.
For instance, we could write:
```rust
#[hax::lemma_statement]
fn my_lemma(x: u32) -> bool {
x * 2 == x + x
}
```
But from Rust's perspective, `my_lemma` was a `u32 -> bool` function, while it is extracted to `u32 -> Lemma ...` in F*.
This PR removes this type difference. Now we write:
```rust
#[hax::lemma]
fn my_lemma(x: u32) -> Proof<{ x * x == x + x }> {}
```
`Proof<*>` is a syntactic convenience, but for now, lemmas are really just unit-returning values.
This makes lemmas easy to call directly from Rust.

feat(macros): improve lemmas

---

Cargo.lock
Cargo.toml
engine/backends/fstar/fstar_backend.ml
hax-lib/Cargo.toml
hax-lib/proofs/fstar/extraction/Hax_lib.fst
hax-lib/src/lib.rs
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
tests/generics/src/lib.rs

This commit adds a crate named `hax-lib`.
This crate contains hax-specific helpers for Rust programs. Those
helpers are usually no-ops when compiled normally but meaningful when
compiled under hax.
For now, essentially, this adds an assert and an assume macro.

feat(hax-lib): intro hax-lib

---

engine/lib/ast_utils.ml
engine/lib/generic_printer/generic_printer.mli
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-coq.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__reordering into-fstar.snap
tests/naming/src/lib.rs

This commit disambiguates record fields by adding type information.
If two record types share some fields, F* just picks the record type that was defined last. This is not fine, thus we add type ascriptions so that F* picks the right type.

feat(engine/fstar): annotate records w/ types for fields disambiguation

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap

I badly merged or rebased something, and that resulted in reverting most of #333, basically :disappointed:
This reapplies the missing bits

fix: reapply badly merged PR #333

---

engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/dependencies.ml
examples/chacha20/proofs/fstar/extraction/Chacha20.Hacspec_helper.fst
examples/chacha20/proofs/fstar/extraction/Chacha20.fst
examples/limited-order-book/proofs/fstar/extraction/Lob_backend.fst
examples/sha256/proofs/fstar/extraction/Sha256.fst
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-coq.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__reordering into-coq.snap
test-harness/src/snapshots/toolchain__reordering into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/reordering/src/lib.rs
tests/traits/Cargo.toml

Due to a very stupid bug, we were generating plain `let`s for instances while we really need `instance`s.
This PR generates now `[@@ FStar.Tactics.Typeclasses.tcinstance]let ...`, which is the same thing as `instance ...`.
F*'s pretty printer doesn't handle the `instance` keyword.
We'll get that prettier output when we'll switch to the generic printer.

fix(engine/fstar): mark `impl`s as F* instances (with an attribute)

---

cli/options/src/lib.rs
engine/backends/proverif/proverif_backend.ml

This includes the reserved words for ProVerif, adds some (for now) pure boilerplate at the beginning and end, and does not much more than is necessary to translate the result of `cargo new --lib mylib` to valid ProVerif with the Rust `fn` translated to an empty `letfun` in ProVerif.

Smallest possible ProVerif backend

---

tests/Cargo.lock
tests/Cargo.toml
tests/proverif-minimal/Cargo.toml
tests/proverif-minimal/src/lib.rs

Include a test in the toolchain test harness that checks whether extraction works for the output of  `cargo new --lib proverif-minimal`.

Minimal example test for ProVerif backend

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__naming into-coq.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
tests/naming/src/lib.rs

This is related to https://github.com/hacspec/hax/pull/362#issuecomment-1812810205. While working with constants, @cmester0 noticed associated constants (i.e. constants in traits) were extracted with different naming schemes according to context.
In Hax, global names are tagged with a kind that gives information about the nature of the identifier: is that an associated item, a type, a field, a value, ...?
The issue is the following:
```rust
const INHERENT_CONSTANT: usize = 3;
trait FooTrait {
const ASSOCIATED_CONSTANT: usize;
}
fn constants<T: FooTrait>() -> usize {
<T as FooTrait>::ASSOCIATED_CONSTANT + INHERENT_CONSTANT
}
```
`ASSOCIATED_CONSTANT` was prefixed with `f_` (this is the prefix for associated items) in `FooTrait` definition, but then prefixed with `v_` in `constants`.
This …

fix(engine): `NamedConsts` are `GlobalVar`s of kind `AssociatedItem Value`

---

engine/lib/concrete_ident/concrete_ident.ml

This PR disables the error @geonnave is hitting (#360), for more info why this is fine for now, see #363

fix(engine): fixes issue #360

---

examples/chacha20/proofs/fstar/extraction/Chacha20.Hacspec_helper.fst
examples/chacha20/proofs/fstar/extraction/Chacha20.fst

I think something went badly at some point when merging, resulting in a duplicated function in F*.
This PR just regenerates the chacha20 example, but I think we should have the CI to fail if the CI generated code is different than the one in the checked in snapshot.

fix(examples/chacha20): regenerate, eliminate duplicated function

---

engine/lib/ast_utils.ml
engine/lib/import_thir.ml
examples/chacha20/proofs/fstar/extraction/Chacha20.fst
examples/limited-order-book/proofs/fstar/extraction/Lob_backend.fst
examples/sha256/proofs/fstar/extraction/Sha256.fst
proof-libs/fstar/core/Alloc.Vec.fst
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-coq.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__reordering into-coq.snap
test-harness/src/snapshots/toolchain__reordering into-fstar.snap
tests/Cargo.lock
tests/attributes/Cargo.toml
tests/attributes/src/lib.rs

Now functions *always* have a arrow type of arity >=1.

fix(engine): make `fn` types always arrows

---

cli/options/src/lib.rs
engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap

Now `cargo hax into fstar` accepts an optional `--interface` flag.
It takes inclusion clauses (similar to `-i`, e.g.  `+module::path::** -module::path::foo::**`).
By default, the backend produces no fsti, but any selected module will have a fsti extraction.

feat(fstar): add `interfaces` flag

---

frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/state.rs
frontend/exporter/src/types/copied.rs

This is related to #273. `opt_def_id` is useful for error reporting, but should not be used anywhere else.
Fixes #273.

refactor(exporter): get rid of `opt_def_id` as much as possible

---

engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/generic_printer/generic_printer_base.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_direct_and_mut.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/print_rust.ml
engine/lib/side_effect_utils.ml
engine/lib/subtype.ml
engine/utils/phase-debug-webapp/static/script.js
frontend/exporter/src/lib.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/Cargo.toml
tests/traits/src/lib.rs

Fixes #370
This PR:
- adds a `Self` kind for `ImplSource`. This is useful for generic information within a trait.
- propagate `impl` on function calls.  
Fixes #20
**Note**: this PR failing is blocking for @cmester0's #349 and #348.
Since this is a bit urgent, my plan is to make failure silent for now: any backend that relies on this feature will then possibly generate bad code if we hit the edge case that currently makes this PR fails.

Add `Self` implsource

---

engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml

This PR adds binder names as much as possible when producing `val` declarations in `fsti` interfaces F* files.
I say "as much as possible" because of issue #402.

fix(engine/fstar): always name binders on `val`s

---

flake.nix

PR #428 added a heavy local dependency to `hax-engine`, a dependency that is expected to be built locally when developing on hax, making compiling the dev environment dependent on the frontend and thus slow.

fix(nix/devshell): make devshell much lighter

---

Cargo.lock
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/phases/phase_cf_into_monads.ml
engine/lib/phases/phase_reconstruct_question_marks.ml
engine/lib/phases/phase_reconstruct_question_marks.mli
engine/lib/side_effect_utils.ml
engine/lib/subtype.ml
engine/lib/utils.ml
engine/names/extract/Cargo.toml
engine/names/src/lib.rs
proof-libs/fstar/core/Core.Num.fsti
proof-libs/fstar/core/Core.Result.fst
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Control_flow_monad.Moption.fst
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Control_flow_monad.Mresult.fst
proof-libs/fstar/rust_primitives/Rust_primitives.fst
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
tests/side-effects/Cargo.toml
tests/side-effects/src/lib.rs

This PR fixes #399 and adds some more tests.

Fix question marks

---

proof-libs/fstar-secret-integers/.envrc
proof-libs/fstar-secret-integers/core/Core.Ops.Index.fst
proof-libs/fstar-secret-integers/core/Core.Ops.Range.fsti
proof-libs/fstar-secret-integers/core/Core.Ops.fst
proof-libs/fstar-secret-integers/rust_primitives/Rust_primitives.Hax.Monomorphized_update_at.fsti
proof-libs/fstar-secret-integers/rust_primitives/Rust_primitives.Hax.fst
proof-libs/fstar-secret-integers/rust_primitives/Rust_primitives.Integers.fsti
proof-libs/fstar/core/Core.Ops.Range.fsti
proof-libs/fstar/core/Makefile

This PR:
- fixes the F* typeclass inference in Core.Ops.Range (cc @karthikbhargavan);
- tweak the makefiles a bit.

Fix core ops range tc

---

.github/workflows/install_and_test.yml
.gitignore
examples/.envrc
examples/README.md
flake.lock
flake.nix
proof-libs/fstar/.envrc

This Pr updates the pinned F* version in the nix files to the latest.

Update F* version to latest release

---

proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Monomorphized_update_at.fsti

I introduced a bug in PR #444, this PR fixes it.

fix(proof-libs/fstar): make implicit a few parameters

---

engine/backends/proverif/proverif_backend.ml
engine/bin/dune
engine/doc/dune
engine/lib/generic_printer/generic_printer.ml
engine/lib/generic_printer/generic_printer_base.ml

This PR allows passing in auxiliary information on creation of a `print` object. This is useful if a generic-printer-based backend requires some information to be collected before doing a certain print pass on the AST, e.g. in the ProVerif backend I want to first scan the AST for function definitions so that I can recognize them during printing at the call-site.
I can imagine other uses as well, e.g. we might not need to insert a full preamble of pre-defined models every time, but only those that are really necessary to model the contents of the AST. Being able to go through the AST once, collecting this information and making it available on later print passes that construct the preamble is a simple solution here as well.

Extend generic printer API with auxiliary information

---

cli/driver/src/driver.rs
cli/driver/src/features.rs
examples/default.nix
tests/mut-ref-functionalization/src/lib.rs

Rustc already (sometimes) uses `stdout` for sending some information, when using `--deps`, rustc sends extra things on `stdout` thus we cannot parse it anylonger.
Fixing #468

fix(cli): use `stderr` for detection mode

---

engine/lib/diagnostics.ml

The `capture` function of `diagnostics.ml` was badly implemented. Seems like in the expression `(f (), g ())` OCaml first runs `g` and then `f`! (see https://try.ocamlpro.com/#code/((fun'_'-$.'prerr_endline'$(A$()'(),'(fun'_'-$.'prerr_endline'$(B$()'()) )
I'm using a state to capture errors, and using `(f (), !state)`, I was ignoring the side effects of `f`, which is... the only point of that `capture` function.

fix(engine/import-thir): fix leaking errors

---

cli/options/src/lib.rs
engine/backends/fstar/fstar_backend.ml
engine/lib/dependencies.ml

feat(engine/fstar): `--interfaces`: add option to extract only `fsti`

---

proof-libs/fstar/rust_primitives/Rust_primitives.Arrays.fsti
proof-libs/fstar/rust_primitives/Rust_primitives.BitVectors.fst
proof-libs/fstar/rust_primitives/Rust_primitives.BitVectors.fsti

This PR adds missing `bit_vec_to_int_t_array` and  `bit_vec_to_nat_array` functions.

feat(proof-lib/fstar): add `bit_vec_to_int_arr` and `bit_vec_to_nat_arr`

---

engine/lib/dependencies.ml

I introduced a bug in https://github.com/hacspec/hax/pull/470: a negative `-i` clause would drop not only the matching items but any items they rely on!
This resulted in an extremely confusing behavior...

fix(engine/deps): fix inverted behavior for including dependencies

---

engine/backends/proverif/proverif_backend.ml

This PR provides coherent translation of crate-internal names, e.g. where before you had `some_function` at the definition site and `crate::some::mod::function` at the call site in another module, you now get `crate__some__mod__some_function` everywhere. Similar for types and their constructors.
Fixes #450.

[ProVerif] Translate crate-internal names

---

engine/lib/import_thir.ml
frontend/exporter/src/traits.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This PR allows to the `Self` impl expression to carry a subpath.
For example with a where clause `where Self::AssocType: SomeTrait`, calling a method `foo` that belongs to `SomeTrait` will use the implementation located at path "Self/AssocItem("AssocType")/Parent("SomeTrait")".
Fixes #482.

Frontend: fix `Self`

---

.github/workflows/install_and_test.yml
README.md
cli/default.nix
engine/default.nix

This PR:
- adds a GitHub action that pushes binaries to Cachix;
- reformulates a bit the README on Nix install;
- add instructions on how to use binary cache when using Nix;
- the OCaml compiler leaves absolute paths to itself inside the binaries it produces... thus this PR also removes such references (otherwise Nix tracks them and the dependency closure contains 500Mb of OCaml compiler).

feat(nix): make derivations lighter, use `cachix`

---

setup.sh

See https://github.com/rust-lang/cargo/issues/6983: by default `cargo install --path ...` doesn't use `Cargo.lock`.
In our case, this caused a rust compatibility issue, because of https://github.com/rust-lang/cargo/issues/9930

fix(cli/setup.sh): `cargo install`: use locked dependencies

---

engine/backends/proverif/proverif_backend.ml
engine/lib/generic_printer/generic_printer.ml

This PR includes a number of updates to the ProVerif backend in order to get syntactically correct ProVerif output when extracting a single function (and some of its dependencies) from the `bertie` codebase. Concretely, the extraction target is `-** +**::tls13handshake::put_server_hello -**::tls13utils::** -**::tls13formats::** -**::tls13crypto::** -**::tls13cert::**`.
The PR includes:
- inserting the already generated field accessor when encountering a field access
- translation of `match`:
```rust
match scrutinee {
pat1 => body1,
pat2 => body2,
...}
```
is translated as
```text
let pat1 = scrutinee in body1
else let pat2 = scrutinee in body2
else ...
```
NB: Translation of patterns is still lacking, anything other than simple binding patterns, which work "by accident" is unlikely to be …

Syntactically correct extraction for one Bertie function

---

engine/lib/print_rust.ml

The following Rust code:
```rust
fn f(x: impl Foo + Bar) {}
```
Is translated as:
```rust
fn f<NAME: Foo + Bar>(x: NAME) {}
```
where `NAME` is actually `impl Foo + Bar`.
This commit recognizes such `NAME` local idents and rename them in the Rust printer.

fix(engine/print-rust): `impl ...` local_idents

---

engine/lib/analyses/mutable_variables.ml
engine/lib/ast_utils.ml
engine/lib/dune
engine/lib/generic_printer/generic_printer.ml
engine/lib/phase_utils.ml
engine/lib/phases/phase_and_mut_defsite.ml

This commit turns missing `!` on methods be an error: if a method is overridden, it should be marked explicitly with `!`.

refactor(engine): enable OCaml warning `7`

---

engine/lib/ast_utils.ml
engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/generics/Cargo.toml
tests/generics/src/lib.rs

This PR fixes the F* extraction of the following kind of code:
```rust
struct Foo;
impl Foo {
fn f<const N: usize>(...) {...} 
}
```
The translation used to drop the const generic `N`, this PR fixes that. 
✔️ I checked, this PR is not breaking Kyber extraction

fix(engine/import): missed generics on inherent impl `fn`s

---

.github/workflows/kyber.yml

This commit adds to CI the extraction to F* of Kyber and TC.
This mostly is a copy-paste from https://github.com/cryspen/libcrux/blob/main/.github/workflows/hax.yml.
Note this job is a bit long, thus it is ran only on when merging in the merge queue.
Status: this is working, but currently Kyber TC is broken, so we need https://github.com/cryspen/libcrux/pull/202 to be merged first

feat(ci): test Kyber extraction and proofs

---

engine/lib/phases/phase_direct_and_mut.ml
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
tests/mut-ref-functionalization/src/lib.rs

fix(engine/direct_and_mut): make sure `out` doesnt shadow

---

cli/default.nix
engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/ast_visitors.ml
engine/lib/concrete_ident/impl_infos.ml
engine/lib/import_thir.ml
engine/lib/import_thir.mli
engine/lib/phases/phase_drop_references.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/deterministic_hash.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This PR:
- **exporter**:
- decorate the paths to impl expressions with `clause_id`s;
- refactor/clean/fixes some code;
- resolve impl expressions and clauses for parent bounds and associated bounds on impl blocks;
- **engine**:
- renames the `trait_ref` AST type into `trait_goal`;
- introduces `impl_ident` in the AST;
- propagate/add the impl idents introduced in the exporter.
In a more high-level view, this PR adds the things missing in the exporter for fully supporting explicit implementation expressions.
I think now we have all the information in hax' AST to extract code with already resolved traits. For instance, we should be able to rework the F* backend so that we don't rely on TC inference on F* side any longer.

feat(exporter/traits): parent bounds on impl and associated types

---

engine/backends/fstar/fstar_backend.ml
frontend/diagnostics/src/lib.rs
hax-lib-macros/src/lib.rs
hax-lib-macros/types/src/lib.rs
test-harness/src/harness.rs
test-harness/src/snapshots/toolchain__attribute-opaque into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/attribute-opaque/Cargo.toml
tests/attribute-opaque/src/lib.rs

This PR:
- introduces `opaque_type` attribute that can mark enums and structs so that their (F* for now) extraction doesn't reveal their definition.
- introduce an option in the test harness so that we can write tests that specify backend options;
- add a test.
Fixes #525

Introduce `opaque_type` attribute

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/index.rs

This commit adds general documentation to the structs and enums defined in `copied.rs`. When a struct or enum is a direct copy from rustc, the documentation just links the original defintion, otherwise I try to add brief documentation on why there is a difference.

doc(frontend): document `copied.rs` file

---

.github/workflows/install_and_test.yml
examples/default.nix
flake.nix

This PR adds a `hax-env` binary to Nix that sets the HAX_PROOF_LIBS, HAX_LIB and HACL_HOME.
So that one can run `eval $(nix run github:hacspec/hax#hax-env)`, this will set environment variable directly.
The nice thing is that every dependency (Hacl, F*, Hax's lib) is frozen and given by hax' Nix flake, so dev environments are very very reproductible.

feat(nix): add a `hax-env` that injects env vars

---

examples/chacha20/proofs/fstar/extraction/Makefile
examples/limited-order-book/proofs/fstar/extraction/Makefile
examples/sha256/proofs/fstar/extraction/Makefile
flake.nix

This commit renames remaining occurences `HAX_PROOF_LIBS` into `HAX_PROOF_LIBS_HOME` and `HAX_LIB` into `HAX_LIBS_HOME`.

fix(f* makefiles): uniformize env vars names

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This commit fixes #536.  The AST of hax has all the information for projected or associated things, but the F* backend doesn't use them much for now. This commit adds support for exactly `Self::WhateverAssociatedType`, but not for more (i.e. parent associated type).

fix(engine): translate associated types to `Self` (e.g. `Self::T`)

---

engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_drop_references.mli

The drop references phases constrained the input language to be question mark free, but it did not make any sense

feat(engine/phases): drop-references: accept `?`

---

examples/chacha20/proofs/fstar/extraction/Makefile
examples/limited-order-book/proofs/fstar/extraction/Makefile
examples/sha256/proofs/fstar/extraction/Makefile
flake.nix
proof-libs/fstar/core/Makefile
proof-libs/fstar/rust_primitives/Makefile

The Makefiles are all over the place (in hax proof libs, hax examples, Bertie, Libcrux), and they don't rely on exactly the same env vars. This commit fixes a few of those differences.
This commit also helps for PR https://github.com/cryspen/libcrux/pull/210.

fix: misc fixes to Makefiles and Nix

---

engine/backends/fstar/fstar_backend.ml
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.fst
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap

This commit changes `array_of_list l` into `array_of_list N l` with `N` a literal. We know `N` at extraction time, so it's free to add, and it's helping type inference, especially in presence of typeclasses.

feat(f*): `array_of_list`: inline the length of the array

---

engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_visitors.ml
engine/lib/dependencies.ml
engine/lib/diagnostics.ml
engine/lib/import_thir.ml
engine/lib/phases.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_drop_sized_trait.ml
engine/lib/phases/phase_drop_sized_trait.mli
engine/lib/phases/phase_traits_specs.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
frontend/exporter/src/traits.rs
frontend/exporter/src/utils.rs
test-harness/src/snapshots/toolchain__attribute-opaque into-fstar.snap
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__include-flag into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This PR:
- propagate parent bounds impl expr and trait information from the frontend to the AST;
- in the F* backend: use this information to populate parent bounds fields;
- introduces a new phase `drop_sized_trait`, that drops the sized trait (which is useless in our backends but extremely verbose).
As a side effect, this also causes some item reordering: now the dependency analysis takes care of parent bounds.
That causes some reordering in the extraction of Kyber, I will push a PR.

F*: insert `solve ()` in impls parent bound fields

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__recursion into-fstar.snap
tests/Cargo.toml
tests/recursion/Cargo.toml
tests/recursion/src/lib.rs

This PR makes the F* backend output a `let rec` for simple recursive functions, not mutual ones.
Supporting mutual recursive functions is trickier because of namespaces, see #44.

Basic rec fstar

---

engine/lib/phases/phase_trivialize_assign_lhs.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/Cargo.lock
tests/attributes/src/lib.rs

The engine used to "monomorphize" `update_at` into specialized versions: in F*, the TC resolution used to slow down a lot typechecking.
However, this monomirphization is wrong in general, so this PR gates this transformation with additional checks on the types.

fix(engine): monomorphize update_at only for vecs, slices and arrays

---

engine/backends/fstar/fstar_backend.ml

PR #572 introduced basic support for non-mutual recursive definitions, but that was working only in the implementation-only mode.
This PR fixes that: `rec` is now insterted in `fst` modules, no matter whether we produce an interface or not.

fix(engine/backend): F*: `rec` qual. when interface mode

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__literals into-coq.snap
test-harness/src/snapshots/toolchain__literals into-fstar.snap
tests/literals/src/lib.rs

This PR adds type annotation for the F* backend on empty array literals.

F*: add type annotations on list literals

---

Cargo.lock
hax-lib/Cargo.toml
hax-lib/src/lib.rs

This PR just re-exports `hax-lib-macros` in `hax-lib`, so that only one dependency is required.

feat(hax-lib): export proc-macros from `hax-lib-macros`

---

cli/subcommands/Cargo.toml
hax-lib-macros/types/Cargo.toml
hax-lib-macros/types/src/lib.rs

This PR makes the schemars dependency optional in the crate `hax-lib-macros`.
Now, `cargo tree` on `hax-lib-macros` gives me:
```
hax-lib-macros v0.1.0-pre.1 (proc-macro) (/home/lucas/repos/hax/main/hax-lib-macros)
├── hax-lib-macros-types v0.1.0-pre.1 (/home/lucas/repos/hax/main/hax-lib-macros/types)
│   ├── proc-macro2 v1.0.69
│   │   └── unicode-ident v1.0.12
│   ├── quote v1.0.33
│   │   └── proc-macro2 v1.0.69 (*)
│   ├── serde v1.0.189
│   │   └── serde_derive v1.0.189 (proc-macro)
│   │       ├── proc-macro2 v1.0.69 (*)
│   │       ├── quote v1.0.33 (*)
│   │       └── syn v2.0.38
│   │           ├── proc-macro2 v1.0.69 (*)
│   │           ├── quote v1.0.33 (*)
│   │           └── unicode-ident v1.0.12
│   ├── serde_json v1.0.107
│   │   ├── itoa v1.0.9
│   │   ├── ryu v1.0.15
│ …
```

feat(hax-lib-macros): dependency `schemars`: make optional

---

engine/backends/fstar/fstar_backend.ml
engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__generics into-fstar.snap
tests/Cargo.lock
tests/generics/src/lib.rs

Default generics are just a nicety provided by Rust, but at the end, Rustc always inline the default when not provided. We don't want to propagate this nicety in the backends, since it's useful only to ease writing new code.
Thus, this PR just drops the default information if any.
Fixes #596

fix(engine): allow default generics

---

cli/options/src/lib.rs
engine/backends/fstar/fstar_backend.ml
engine/bin/lib.ml
engine/lib/dependencies.ml
engine/lib/import_thir.ml
engine/lib/import_thir.mli
engine/names/src/lib.rs
hax-lib-macros/src/lib.rs
hax-lib-macros/src/utils.rs
hax-lib-macros/types/src/lib.rs
test-harness/src/snapshots/toolchain__interface-only into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/cli/interface-only/Cargo.toml
tests/cli/interface-only/src/lib.rs

This PR adds the `+:` modifier to inclusion clauses. `-i '... +:some::glob::pattern'` will extract signature-only for the items matched by `some::glob::pattern`.
I added some doc in the book, see https://github.com/hacspec/book/pull/15

feat: include flag: allow for dropping bodies

---

engine/backends/fstar/fstar_ast.ml
test-harness/src/snapshots/toolchain__traits into-fstar.snap

The F* backend used to generate calls `solve ()`, instead we need `solve` with no argument at all.
This PR does this change.

fix(fstar): `Typeclasses.solve` takes no argument

---

engine/backends/fstar/fstar_backend.ml
engine/lib/import_thir.ml
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__include-flag into-fstar.snap
test-harness/src/snapshots/toolchain__interface-only into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
tests/attributes/src/lib.rs

This PR:
- makes hax detect `#[doc = "..."]` as a doc comment
- fixes a couple of issues with doc comments in hax' AST
- make the F* backend outputs comments

Improve doc comments, output them in F*

---

engine/names/extract/build.rs
test-harness/src/command_hax_ext.rs

This commit fixes the test harness: since
https://github.com/hacspec/hax/pull/428, the test harness silently assumes hax is in PATH while building the crate
`hax-engine-names-extract`.
This crate `hax-engine-names-extract` is used at build time by the engine to list and import the Rust names we rely on.
`hax-engine-names-extract` itself requires the Rust part of hax at build time.
This PR fixes the test harness so that:
1. it asks cargo to build `cargo-hax` and the driver
2. it looks for the path of `cargo-hax` & driver just built (somewhere local in `target/bin/something/someting`), injects thoses paths as env vars in a `cargo build --bin hax-engine-names-extract`;
3. it compiles the engine with the three paths mentioned above (which are required by the engine at compile time);
4. it …

fix(test-harness): `hax-engine-names-extract` needs hax in PATH

---

test-harness/src/command_hax_ext.rs

The `cargo build --bins` command was ran in the directory of the test harness, resulting in a no-op. This commit sets the current dir to the root of the repository so that binaries are indeed built.

fix(test-harness): set `current_dir`

---

Cargo.lock
Cargo.toml
engine/backends/fstar/fstar_backend.ml
engine/lib/diagnostics.ml
engine/lib/phases/phase_specialize.ml
engine/lib/phases/phase_specialize.mli
engine/lib/utils.ml
engine/names/src/lib.rs
hax-lib-macros/src/lib.rs
hax-lib/Cargo.toml
hax-lib/proofs/fstar/extraction/Hax_lib.Int.fst
hax-lib/proofs/fstar/extraction/Makefile
hax-lib/src/int/bigint.rs
hax-lib/src/int/mod.rs
hax-lib/src/lib.rs
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Int.fst
test-harness/src/snapshots/toolchain__literals into-coq.snap
test-harness/src/snapshots/toolchain__literals into-fstar.snap
tests/Cargo.lock
tests/literals/Cargo.toml
tests/literals/src/lib.rs

This PR adds support for math integers. Will fix #607.
This PR:
- introduces a `Int` type  (for math integers) that implements common operations;
- translate `Int` as primitive `int` in F*, and same thing for methods on `Int`;
- introduces a Specialize phase that "monomorphize" operations (e.g. std's add becomes a specific function);
- provides a `int` macro for math int literals;
- adds tests for math ints and their operations.

Add support for math integers

---

proof-libs/fstar/core/Core.Core_arch.X86.fsti

This fixes an F* type error for code that uses AVX2.

setting universe 0 for SIMD vector type

---

.utils/rebuild.sh
setup.sh

This PR makes the `rebuild.sh` use OPAM prefix if possible, and also adds a warning if using `setup.sh` in a drity checkout of hax, hinting the use to use the rebuild script.

feat(setup/rebuild): use OPAMs prefix if possible

---

engine/lib/import_thir.ml
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This PR fixes #474.
The issue in #474 was about opaque types. An opaque type is an existential type: there exists a type for which some traits are implemented.
When looking at an opaque type, we were not including those implemented traits, resulting in systematic failures.
This PR fixes that, and also improves the `subts` function from the ext trait `SubstBinder` (as spotted by @Nadrieril: we were not re-wrapping binders after substs them!).

Exporter: fix #474

---

.envrc
Cargo.lock
Cargo.toml
engine/lib/phases/phase_newtype_as_refinement.ml
engine/names/src/lib.rs
examples/Cargo.lock
examples/Cargo.toml
examples/barrett/proofs/fstar/extraction/Makefile
examples/chacha20/Cargo.toml
examples/chacha20/proofs/fstar/extraction/Chacha20.fst
examples/chacha20/proofs/fstar/extraction/Makefile
examples/chacha20/src/lib.rs
examples/default.nix
examples/kyber_compress/proofs/fstar/extraction/Makefile
examples/limited-order-book/Cargo.toml
examples/limited-order-book/proofs/fstar/extraction/Makefile
examples/sha256/proofs/fstar/extraction/Makefile
hax-bounded-integers/Cargo.toml
hax-bounded-integers/proofs/fstar/extraction/Hax_bounded_integers.Num_traits.fst
hax-bounded-integers/proofs/fstar/extraction/Hax_bounded_integers.fst
hax-bounded-integers/src/lib.rs
hax-bounded-integers/src/num_traits.rs
hax-lib-macros/src/lib.rs
hax-lib/proofs/fstar/extraction/Makefile
hax-lib/src/lib.rs
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.fst
tests/attributes/src/lib.rs

This PR:
- renames the method `refine` (from the trait Refine, which is implemented by types for which refine types have been defined) into `check` ("check" is less "refinement-oriented" vocabulary and conveys the right intuition);
- adds an `invariant` method to the `Refinement` trait, so that one can check whether a value satisfies a refinement;
- use that `invariant` method to generate a `debug_assert!` that ensures the refinement holds at runtime (in debug mode only);
- add a `no_debug_runtime_check` option to disable that runtime check even in debug mode (useful since that check requires the refined type to impl `Clone`);
- introduces a module `num_traits` that defines a small trait hierarchy for operations we want to support on machine integers;
- introduces a series of refined type …

Bounded integers

---

engine/lib/ast.ml
engine/lib/ast_visitors.ml
engine/lib/import_thir.ml
engine/lib/subtype.ml
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
proof-libs/fstar/core/Alloc.Collections.Binary_heap.fsti
rust-toolchain.toml
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This feels like enough changes for one PR.

Bump rustc version by a few weeks

---

.github/workflows/install_and_test.yml
.github/workflows/test_installs.yml

The https://github.com/hacspec/specs repository contains specifications written in hacspec, mainly at the time of hacspec v1.
Since hacspec v1 is deprecated and archived, its library is deprecated as well.
The hacspec lib (https://github.com/hacspec/hacspec/tree/master/lib) doesn't typecheck any longer with `num-bigint` version `0.4.5`.
The hacspec lib dependents on `num-bigint` version `0.4`, not specifying the minor version. The `specs` repository has no `Cargo.lock`, and thus, from a clean `git clone`, `cargo build` pins `num-bigint` to version `0.4.5`, breaking the hacspec library.
This broke https://github.com/hacspec/hax/pull/653 recently, and we had the same kind of errors a couple times before in the past.
Two options were considered:
- remove the tests related to the specs in the …

fix(ci): remove `specs` tests

---

.github/workflows/install_and_test.yml
.github/workflows/test_installs.yml
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.fst

This PR fixes the F* library to reverse the order in which the Index trait is resolved.
This is needed to fix the libcrux CI.

library fix for libcrux ci

---

.github/workflows/engine_js_build.yml
CI.md
engine/bin/dune
engine/bin/dune-js
engine/default.nix

This PR disables the dune JS build of the engine by default.
For now, this build is never used.

fix(engine/dune): disable js build by default

---

Cargo.lock
PUBLISHING.md
hax-lib-macros/Cargo.toml
hax-lib-macros/README.md
hax-lib-macros/types/Cargo.toml
hax-lib-macros/types/README.md
hax-lib/Cargo.toml
hax-lib/README.md

This sets some more values for hax-lib crates and updates publishing.md.
When this is in let's publish a first round.

prepare hax-lib for publishing

---

engine/backends/coq/dune
engine/bin/dune
engine/bin/lib.ml
engine/lib/import_thir.ml
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/state.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/mir_traits.rs
rust-toolchain.toml
test-harness/src/snapshots/toolchain__traits into-fstar.snap

Some interesting clause-related changes.
Regarding `Clause` hashing, I think we should either never hash the binder or prevent hashing without a binder; the current middle-ground is error-prone. Consistently ignoring the binder seems fine.

Bump rustc version

---

.github/workflows/push_readme.yml

This PR adds a GH action that automatically pushes the README from this repo to `hacspec/hacspec.github.io` repo.
It's also adding a comment in the README `hacspec/hacspec.github.io` repo to discourage edits, and changes the "Website" link into a "Github" link. 
Note: I tested the action, it's working fine!

Sync hax readme with `hacspec.github.io`

---

engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__attribute-opaque into-fstar.snap
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__include-flag into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap

Using `Type` causes issues, especially in interfaces. An interface with a function with an implicit type parameter typed `Type` means that its universe could be anything, which will never occur in code generated from Rust.
See also https://github.com/cryspen/libcrux/pull/277
There is a dependency cycle in term of CI, thus I remove the workflow that extract Kyber from the mandatory jobs for now, will

fix(F*): always use `Type0`, never `Type`

---

engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/ast_visitors.ml
engine/lib/generic_printer/generic_printer_base.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_direct_and_mut.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_specialize.ml
engine/lib/print_rust.ml
engine/lib/side_effect_utils.ml
engine/lib/subtype.ml
frontend/exporter/src/types/copied.rs

This PR fixes #668 by:
- fetching impl expressions for bounds on function calls in THIR and inlining that information in the AST of hax' frontend;
- propagate this information in the engine by adding a similar field on applications in the engine AST.
This change is required for #667, but this PR only adds the impl information internally. This PR does nothing with this information. That's why this PR doesn't add any test.

Add bounds impls on calls in expressions

---

frontend/exporter/src/constant_utils.rs

That was a simple oversight in the handling of constants: we hadn't tried top-level unevaluated constants, which occur at least for top-level constants coming from a foreign crate.
This is the fix for https://github.com/AeneasVerif/charon/issues/175.

Fix handling of unevaluated top-level constants

---

frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/Cargo.toml
tests/traits/src/lib.rs

This PR:
- fixes #495 by turning an error into a warning with some debugging context;
- fixes another similar bug when a bound is universally quantified by a lifetime (See the tests introduced by the first commit. When comparing two predicates, we were not systematically erasing regions, causing a bound `for<'a> Foo<&'a T>` not being selected when looking for a `Foo<&T>`.).

Frontend: silence an error about escaping bounded variables

---

engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
examples/Cargo.lock
examples/barrett/proofs/fstar/extraction/Makefile
examples/chacha20/proofs/fstar/extraction/Chacha20.Hacspec_helper.fst
examples/chacha20/proofs/fstar/extraction/Chacha20.fst
examples/limited-order-book/proofs/fstar/extraction/Lob_backend.fst
examples/sha256/proofs/fstar/extraction/Sha256.fst
proof-libs/fstar/core/Alloc.Collections.Binary_heap.fsti
proof-libs/fstar/core/Alloc.Vec.fst
proof-libs/fstar/core/Core.Cmp.fsti
proof-libs/fstar/core/Core.Option.fst
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__include-flag into-fstar.snap
test-harness/src/snapshots/toolchain__loops into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This PR fixes issue #677, which describes the problem in more lengths.
This will break heavily Kyber, so I will push a companion PR on libcrux.
Fixes #677

Engine: F*: fix #677 by always extracting implicit types

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/mir_traits.rs

This PR makes the exporter always use `s.param_env()` instead of `s.base().tcx.param_env(s.owner_id())`.
Status: any merge in hax is blocked by https://github.com/hacspec/hax/pull/679, I'm fixing that PR

refactor(exporter): always use `State::param_env`

---

engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js

The new version of ppx_deriving was extremely slow. ppx_deriving used to discard extra deriving annotations on type bundles, but it seems like it does not any longer. This PR fixes the JS script that generates the ocaml module `types.ml` so that it generates only one last annotation instead of one on each type. This fixes the issue (see the CI link below).
**old status:**
- pinning ppx_deriving works, but I'm trying another fix to stop it from looping. Also, it seems like it's just extremely slow, not endlessly looping. My JS script generates a deriving clause per type, while only one at the end is enough. That is probably what is causing the extreme slowness.
- I'm waiting to see if https://github.com/hacspec/hax/actions/runs/9347802540/job/25725550131 is green
**Status:**
The fix works, …

fix(ci): newer version of `ppx_deriving` (6.0.2) loops indefinitely

---

.github/workflows/push_readme.yml
README.md

This PR makes relative links in the README always start with a `./`, and makes the "push README" action rewrite such path that starts with `./` into absolute links.
Closes #701

fix(README): always begin relative path with `./`, rewrite in action

---

Cargo.lock
PUBLISHING.md
cli/subcommands/src/cargo_hax.rs
engine/names/extract/Cargo.toml
engine/names/extract/build.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/def_id.rs
frontend/exporter/src/types/mod.rs
frontend/exporter/src/types/replaced.rs

The OCaml build depends on the binary `hax-engine-names-extract`, which, at build-time, depends on the hax frontend.
`hax-engine-names-extract` runs the frontend at build time on `hax-engine-names`, which itself used to depend on the crate `hax-engine-frontend`. Running hax however sets specific cfg flags, yielding recompilations.
This PR cut the dependency between `hax-engine-names` and `hax-engine-frontend`. `hax-engine-names` needs only three type definitions from `hax-engine-frontend`: this PR isolates those three types in a module, and  makes `hax-engine-names` directly use that module, inlined.

feat: isolate `DefId`: faster build times

---

Cargo.toml
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs

This PR makes hax built with release mode ship with all logs available.
It also adds some logs on trait functions.

feat(hax): logging: enable tracing in release, add trait-related logs

---

README.md
engine/backends/fstar/fstar-surface-ast/FStar_String.ml
flake.lock
flake.nix
frontend/exporter/src/types/copied.rs

This PR updates the engine to OCaml 5

Update to OCaml 5

---

engine/backends/fstar/fstar_backend.ml

Parent bounds are translated as record fields in F*.  Also, F* classes
are records, and F* records cannot be empty. Thus, we insert a dummy
field `__marker_trait` on empty traits (marker traits).
On trait definitions, we were inserting this `__marker_trait` fields
only when a trait had no parent bounds and no associated item (method,
assoc. type, assoc fun.).
On instance definitons, we were inserting `__marker_trait` when the
trait was empty, disregarding parent bounds.
This difference of treatments lead to TC issues in F*.
This PR fixes this discrepancy.

fix(backends/fstar): no `__marker_trait` if parent bounds

---

engine/default.nix
flake.nix

This PR:
- remove some rustc runtime dependencies in the nix build of hax-engine;
- renames the nix derivation of the hax engine.
After this PR, `nix bundle --bundler github:ralismark/nix-appimage ".#hax-engine.bin"` produces a 21M self contained portable AppImage!

feat(nix): reduce closure size for hax-engine

---

.github/workflows/mlkem.yml

This PR just renames the action that extracts ML-Kem from `hax` to `extract-mlkem`. Having this workflow named `hax` was very confusing (`git blame` blames myself sadly 😅).
Note: when merging this PR, we'll need to change the required jobs for merging in `main`

fix: rename action for extracting ml-kem

---

frontend/exporter/src/index_vec.rs
frontend/exporter/src/types/copied.rs

The discriminant is the runtime integer value used to identify a given enum variant. It's the value on which we do a `SwitchInt`. This PR makes hax export them.
I would have prefered a `discriminant` field in `VariantDef` but that would have been tricky to fit into the `SInto` scheme.

Export discriminant values in `AdtDef`

---

Cargo.lock
engine/lib/phases/phase_newtype_as_refinement.ml
engine/names/src/lib.rs
hax-bounded-integers/Cargo.toml
hax-bounded-integers/proofs/fstar/extraction/Hax_bounded_integers.Num_traits.fst
hax-bounded-integers/proofs/fstar/extraction/Hax_bounded_integers.fst
hax-bounded-integers/src/lib.rs
hax-bounded-integers/src/num_traits.rs
hax-lib-macros/src/lib.rs
hax-lib/src/lib.rs
proof-libs/fstar/core/Core.Num.fsti
proof-libs/fstar/core/Core.Ops.Arith.fsti

This PR refactors the macros in `hax-bounded-integers` and exposes a new `refinement_int` macro that behaves liuke `refinement_type`, but also derives "all" instances we'd expect from an integer type.

Generalize bounded ints

---

cli/options/src/lib.rs
engine/bin/lib.ml
frontend/exporter/src/state.rs
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This commit disables trait resolution in the context of a type alias definition.
Rust doesn't enforce bounds on generic parameters in type aliases, so it is legal to write:
```rust
struct Foo<T: Clone>(T);
type Synonym<T> = Foo<T>;
```
Thus, if we compute the impl expression for the bound `T: Clone` that appears on the type expression `Foo<T>`, Rustc's trait selection fails: in the context of `Synonym`, `T` indeed doesn't implement `Clone`, _a priori_.
This is raising an issue about backends: translating such type synonyms with "missing" bounds will fail. See
https://github.com/hacspec/hax/issues/708. Thus, this PR also introduces an option so that type synonyms are not extracted by default.
Fixes #707 and fixes #708

fix(exporter): disable impl expr resolution under type aliases

---

.github/workflows/install_and_test.yml
engine/backends/fstar/fstar-surface-ast/z.ml

This is a small fix in the engine so that we use `Base.String.hash` instead of `String.hash`, which is only available in most recent versions of OCaml.
This is required to fix a failing `setup.sh` job

fix(engine/fstar): use `Base.String.hash` instead of `String.hash`

---

engine/lib/import_thir.ml
frontend/exporter/src/types/copied.rs

This PR separates method generic args and trait generic args of the `call` nodes of THIR expressions.
Consider the following example:
```rust
trait MyTrait<TraitType> {
fn meth<MethType>(...) {...}
}
fn example_call<TraitType, SelfType: MyTrait<TraitType>>(x: SelfType) {
x.meth::<String>(...)
}
```
Before this commit, the call `x.meth::<String>` produced a `Call` node whose field `generic_args` was `[SelfType, TraitType, String]`.
Now, that `Call` node has a trait-specific generic arguments field `[SelfType, TraitType]` and a method/function-specific generic arguments field `[String].`
This commit does no change to the engine, that will be for a subsequent PR.
This PR is related to #719.

feat(exporter): thir: call: separate trait VS method generic args

---

.github/workflows/test.yml
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/lib.rs
frontend/exporter/src/state.rs
frontend/exporter/src/types/copied.rs

This PR removes some use of nightly features or feature-gate them, based on the `rustc` feature introduced by #743.
This is useful for Rust projects that depend on the ASTs of hax but not on librustc_driver (e.g. Testify).
Fixes #749

 exporter: make it need nightly only when feature `rustc` is on

---

engine/utils/ppx_functor_application/README.md
engine/utils/ppx_functor_application/ppx_functor_application.ml

doc(engine): ppx_functor_application

---

.utils/rebuild.sh

The rebuild script uses the `\e` argument to print in different colors.
But the `\e` encoding is not supported in all shells, whereas `\033` should be widely supported.

fix color printing in util script

---

hax-lib-macros/src/lib.rs

This commit fixes #761.
Considering:
```rust
use some::path::to::T;
pub struct MyRefinedType(T);
```
The generated code wraps the struct declaration in a module. That module used not to have `T` in scope.
This commit adds a `use super::*` before declaring the type of the refinement type.

fix(hax-lib): `use super::*` in refinement expansion

---

cli/driver/src/exporter.rs
hax-types/src/driver_api.rs

This commit removes the field `crate_type` in the struct `HaxMeta`, and changes the path of `haxmeta` files.
Originally, my intention was to name the `haxmeta` files very closely to `rmeta` files, but the `haxmeta` don't have anything to do with crate types.
Also, the code was assuming a crate would have only one type, which is false, as the type suggests... That was making the frontend panic on certain crates.

fix(frontend): kill `crate_type` in `HaxMeta`

---

cli/subcommands/src/cargo_hax.rs
engine/lib/phases/phase_newtype_as_refinement.ml
hax-lib/proofs/fstar/extraction/Hax_lib.Int.fst
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR:
- fixes a bad F* file in the library
- fixes a bug where `f(y.get()).get()` would rewrite `f(y.get()).get()`, but not the inner `y.get()`, and adds a test for that
- fixes an unrelated bug abound prettyplease panicking on `unimplemented!`

fix(hax-lib): refinements: various fixes

---

engine/backends/fstar/fstar-surface-ast/FStar_Parser_Const.ml
engine/backends/fstar/fstar_ast.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_direct_and_mut.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/phases/phase_reconstruct_question_marks.ml
engine/lib/phases/phase_simplify_question_marks.ml
engine/lib/phases/phase_specialize.ml
engine/lib/side_effect_utils.ml
engine/lib/subtype.ml
proof-libs/fstar/core/Core.Ops.Deref.fst
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__include-flag into-fstar.snap
test-harness/src/snapshots/toolchain__interface-only into-fstar.snap
test-harness/src/snapshots/toolchain__loops into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

~This PR requires #698.~
This PR propagates trait generics arguments throughout the engine.
On the F* output:
- now the calls to methods will always be `method #self_type #trait_generic_arg1 ... #trait_generic_argN #Typeclasses.solve #method_generic_type1 ... #method_generic_typeM method_generic_const1 ... method_generic_constI meth_arg1 ... meth_argJ`
- traits and inductive (enums/structs) should have all their argument explicit
Todo:
When undrafted, this PR should fix #719

Engine: propagate trait generics arguments

---

hax-lib-macros/src/lib.rs
hax-lib-macros/src/syn_ext.rs
hax-lib-macros/src/utils.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

Fixes #755 and fixes #290.
This allows this kind of post-conditions:
```rust
#[hax::requires(*x < 40 && *y < 300)]
#[hax::ensures(|result| *future(x) == *y && *future(y) == *x && result == *x + *y)]
fn swap_and_mut_req_ens(x: &mut u32, y: &mut u32) -> u32 {
let x0 = *x;
*x = *y;
*y = x0;
*x + *y
}
```

feat(hax-lib): allow requires & ensures on `&mut` inputs functions

---

book/default.nix
book/postprocess.sh

The book uses custom checkboxes in the quickstart chapter. When we moved the book to this repo (see
https://github.com/hacspec/hax/pull/729), we dropped the theme.
mdbook documentation suggest (see
https://rust-lang.github.io/mdBook/format/theme/index.html) copying and patching the default theme.
Since here it's such a small change, I added a small script that post-process the HTML instead.

feat(book): fix checkboxes

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

PR #790 was outputting `pre_instance => pre_trait` for precondition.
We need the opposite: the precondition of the instance should always be implied by the one defined on the trait.

fix: precondition constraints should be of the shape `true => pred`

---

hax-bounded-integers/src/lib.rs

This PR fixes a bug @maximebuyse spotted while we were looking at the bounded integers crate: `one` and `zero` were inverted...

fix(bounded-ints): zero and one were inverted

---

engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js

`val` is not a keyword in Rust, but is in OCaml, so it should be renamed by the script that generates OCaml types, parsers and serializers.
This PR adds an exhaustive list of OCaml keywords to the list of words that should get rewritten.
Thanks @Nadrieril for bringing that up!

feat(engine/ocaml_of_json_schema): add `val` to keyword list

---

Cargo.lock
cli/subcommands/Cargo.toml
cli/subcommands/src/cargo_hax.rs
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
hax-types/src/cli_options.rs
hax-types/src/diagnostics/message.rs
hax-types/src/diagnostics/mod.rs
hax-types/src/diagnostics/report.rs

This PR adds an option `--message-format` to output hax messages as JSON, just as `cargo` does.
`--message-format` can be set either to `human` (the default), or `json`.
When `--message-format` is set to `json`, `cargo` commands will be run with `--message-format json` as well, unless Cargo's own `--message-format` flag is explicitly set (e.g. via `cargo hax -C --message-format human ; ...`).
This feature is useful for external programs that might want to consume machine-readable output from hax.

Add json format option

---

frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/new/predicate_id.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

Fixes #692
Status: seems like this is introducing a bug, I have to debug.
Some implementations cannot be found after the change

fix(frontend): make `path_to` breadth-first

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/easycrypt/easycrypt_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/backends/proverif/proverif_backend.ml
engine/lib/ast.ml
engine/lib/diagnostics.ml
engine/lib/features.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_and_mut_defsite.ml
engine/lib/phases/phase_reject.ml
engine/lib/phases/phase_traits_specs.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml

Address #624 in the importer.
This PR adds a `TIDefault` variant to `trait_item'` in the AST to support trait items with default values/implementations.
Currently, only defaults in `const` and `fn` are supported where `const`s are encoded with a arity-0 function just like normal trait items.
Defaults for associated types are not currently supported as they are still an unstable feature in upstream rust [https://github.com/rust-lang/rust/issues/29661](https://github.com/rust-lang/rust/issues/29661).
This addition is feature gated with the `trait_item_default` feature and all backends have been adjusted to reject this feature for the moment.

feat(engine): add feature for trait item defaults

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__dyn into-fstar.snap
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap

For a method `f` in a trait, we generate two fields: `f_pre` and `f_post`. Those used to be boolean predicates, because we inherited the type from Rust. This commit changes that: we now enforce `f_pre` and `f_post` to be arrow type with `Type0` as last component.

fix(backend/fstar): pre/post are `Type0` predicates, not boolean predicates

---

Cargo.lock
engine/lib/phases/phase_transform_hax_lib_inline.ml
engine/names/src/lib.rs
hax-lib-macros/Cargo.toml
hax-lib-macros/src/lib.rs
hax-lib-macros/src/quote.rs
hax-lib-macros/src/utils.rs
hax-lib/src/lib.rs
hax-lib/src/proc_macros.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/Cargo.lock
tests/attributes/src/lib.rs

Closes #825.
(note: replace BACKEND by `fstar`, `coq`, etc. in the text of this PR)
This PR:
- adds `hax_lib::inline_unsafe` function, hidden in documentation, that allows to inline BACKEND code of any type directly as an expression. This is an internal function, it not supposed to be used directly. ~It exists only when compiling through hax~ (see my last reverted commit). The body of this function is an `unreachable!`.
- adds a `hax_lib_macro:BACKEND_unsafe_expr` macro (exposed as `hax_lib::BACKEND_unsafe_expr`, hidden in doc) which leverages `inline_unsafe` to produce inlined BACKEND code of any type.
- exposes `hax_lib_macro:BACKEND_unsafe_expr` locally as `BACKEND` in pre and post conditions. Thus we can use e.g. `fstar!("forall x. ...")` in ensures and requires clauses.
- Disallow …

Add unsafe versions of inlining macros

---

engine/backends/fstar/fstar_backend.ml
engine/lib/diagnostics.ml
engine/lib/phases/phase_hoist_disjunctive_patterns.ml
engine/lib/phases/phase_hoist_disjunctive_patterns.mli
test-harness/src/snapshots/toolchain__pattern-or into-coq.snap
test-harness/src/snapshots/toolchain__pattern-or into-fstar.snap
tests/pattern-or/src/lib.rs

Closes #463.
We add a new monomorphic phase that lifts up all deep disjunctive patterns so that the resulting patterns may only contain shallow disjunctions.
For example the pattern `(1 | 2, Some(3 | 4))` is transformed as `(1, Some(3)) | (1, Some(4)) | (2, Some(3)) | (2, Some(4))`

Eliminate deep disjunctive patterns.

---

engine/backends/fstar/fstar_backend.ml
hax-types/Cargo.toml
hax-types/src/cli_options.rs

This PR introduces the option `--line-width` (and a corresponding env var) on the F* backend. This controls the max line width for the pretty-printer.

feat(engine/backend/F*): intro --line-width: control pretty printer

---

hax-lib-macros/src/lib.rs
hax-lib/src/proc_macros.rs

@karthikbhargavan @mamonet that's what we discussed:
```rust
#[hax_lib::fstar::verification_status(panic_free)]
#[hax_lib::requires(x < 30)]
#[hax_lib::ensures(|_|
/*something hard to prove, symbolized by false here*/
false
)]
fn f(x: u8) -> u8 {
x + x
}
#[hax_lib::fstar::verification_status(lax)]
fn g(x: u8) -> u8 {
x + x
}
#[hax_lib::fstar::options("--z3rlimit 1234")]
fn h(x: u8) -> u8 {
x + x
}
```
<sup>&nbsp;&nbsp;&nbsp;[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/526fc073dc/gist=09e66ea206ccaca45ff4021b553515fa)</sup>

feat(hax-lib/f*): add `verif_status` and `options`

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__naming into-coq.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
tests/naming/Cargo.toml
tests/naming/src/lib.rs

fix(engine/fstar): add `string` to the list of protected names

---

engine/backends/fstar/fstar_backend.ml
hax-lib-macros/src/lib.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR:
- pushes options/verif status to fst instead of fsti
- adds a comment "panic freedom" just after the admit with verif option

F*: macros: make `verification_status` and `options` appear in impl not interfaces

---

hax-lib-macros/src/utils.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

Fixes #844, and #845
Fixes this kind of code:
```rust
#[hax_lib::ensures(|_| true)]
fn issue_844(_x: &mut u8) {}
// From issue #845
mod ensures_on_arity_zero_fns {
#[hax_lib::requires(true)]
#[hax_lib::ensures(|_x| true)]
fn doing_nothing() {}
#[hax_lib::requires(true)]
#[hax_lib::ensures(|x| x > 100)]
fn basically_a_constant() -> u8 {
127
}
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/39e78de54a/gist=09a2c04c79357028d363a24cefba0889)

Fix ensures for unit-returning functions with &mut inputs

---

cli/subcommands/src/cargo_hax.rs
hax-types/src/diagnostics/message.rs

This PR:
- prints relative paths instead of absolute ones in hax note messages
- write files only when a file doesn't exists or has a different content as what we were about to write
- prints the notice message `hax: unchanged file <path>` instead of `hax: wrote file <path>` in those cases
This is useful not to invalidate checked files in caches while typechecking F*

fix(cli): when we generate a file that exists and has the same content, skip writing

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__literals into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
test-harness/src/snapshots/toolchain__slices into-fstar.snap

Subsumes #854: this PR removes entirely `unsize` calls whenever it is called on arrays, in the F* backend.
The advantages are:
- no unsize calls at all
- easy to support other kinds of unsize which might not be identity, just by adding F* instances (or go the full way and hardcode something in the engine)

Remove unsize for certain types

---

.utils/list-names.sh
engine/lib/ast_utils.ml
engine/lib/phases/phase_functionalize_loops.ml
engine/lib/utils.ml
engine/names/src/lib.rs
flake.nix
hax-lib-macros/src/lib.rs
hax-lib/src/lib.rs
hax-lib/src/proc_macros.rs
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Folds.fsti
test-harness/src/snapshots/toolchain__generics into-fstar.snap
test-harness/src/snapshots/toolchain__loops into-fstar.snap
test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
tests/Cargo.lock
tests/loops/Cargo.toml
tests/loops/src/lib.rs

This PR recognizes and transforms in a particular way the following loops. It also injects invariants.
```rust
fn range() {
let mut count = 0u64;
for i in 0u8..10u8 {
hax_lib::loop_invariant!(|i: u8| i <= 10);
count += 1;
}
}
fn range_step_by() {
let mut count = 0u64;
for i in (0u8..10u8).step_by(2) {
hax_lib::loop_invariant!(|i: u8| i <= 10);
count += 1;
}
}
fn enumerated_slice<T>(slice: &[T]) {
let mut count = 0u64;
for i in slice.into_iter().enumerate() {
hax_lib::loop_invariant!(|i: usize| i <= 10);
count += 2;
}
}
fn enumerated_chunked_slice<T>(slice: &[T]) {
let mut count = 0u64;
for i in slice.chunks_exact(3).enumerate() {
hax_lib::loop_invariant!(|i: usize| { fstar!("$i <= ${slice.len()}") });
count += 3;
}
}
```
[Open this code snippet in the …

Loop invariants

---

engine/backends/fstar/fstar_backend.ml
engine/lib/attr_payloads.ml
engine/lib/phases/phase_traits_specs.ml
engine/lib/utils.ml

This PR removes a few calls to exception-throwing functions in the engine, and replaces them with total variant that returns errors. Then this PR prints those error in a nicer way so that:
- we get a Rust location
- we get more info on what went wrong

engine: kill a few `exn` to get useful errors

---

.utils/expand.sh
engine/lib/attr_payloads.ml
engine/lib/phases/phase_traits_specs.ml
flake.nix
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR simplifies and fixes the extraction of post-conditions in the presence of &mut inputs in impl blocks.

Pre post impl blocks

---

engine/lib/phases/phase_specialize.ml

Fixes #875 
The recursive call on the arguments was done twice in some cases which leads to an exponential complexity. The fix is just to avoid the double recursive call.

Avoid recursing twice on the arguments.

---

proof-libs/fstar/core/Core.Option.fst

This is an attempt at adding support for `Option::map` in the F* model of the Rust core library.
The model is copied from the existing one of `Option::and_then`, with the return type of the closure being adapted.
Is there any additional integration/unit tests to write for these models?

fix(fstar-core): add support for `Option::map`

---

hax-types/src/diagnostics/report.rs

Fixes #879 
The crate `annotate-snippets` that we use for reporting error messages has a parameter `line_start` that corresponds to the line number of the first line that we pass (the source code is passed as a string in another parameter). In our case we always give the full source code so `line_start` should be 1 (and not the line number at which the error is located).

Fix incorrect line numbers in error messages

---

proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Folds.fsti

I run into case where index boundaries need to be precise for `fold_range_step_by`, let's consider the following case
```
Rust_primitives.Hax.Folds.fold_range_step_by 0ul
32ul
(sz 4)
(fun sampled_i16s temp_1_ ->
true)
sampled_i16s
(fun sampled_i16s outcome_set ->
sampled_i16s)
```
The steps are the following `[0, 4, 8, 12, 16, 20, 24, 28]` so the boundary for index is `i <= 28` but by default I get `i < 32` by the condition `v i < v end_` in `fold_range_step_by`, I adjusted that with proper condition in this PR.

Fix step boundaries in fold_range_step_by

---

engine/bin/lib.ml
engine/lib/dependencies.ml
engine/lib/dependencies.mli
engine/lib/diagnostics.ml
engine/lib/phases/phase_newtype_as_refinement.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap

This PR makes the engine include requires/ensures (and other such associated items) of all included functions.
It also fixes the dependency analysis to account for requires and ensures clauses.
Fixes #859

fix(engine): make dep. analysis sensible to UID assoc. items

---

proof-libs/fstar/core/Core.Default.fsti

Fixes the definition of the `default` trait in the F* core lib.
The previous definition was incorrect: names were wrong, and pre/post fields were missing.
Fixes #585.

fix: fstar: default trait

---

engine/lib/import_thir.ml
frontend/exporter/src/deterministic_hash.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/mir_traits.rs
frontend/exporter/src/types/new/predicate_id.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This is a bunch of small fixes we made while working together with @W95Psp on the binders issue. I kept the non-controversial changes and cleaned them up.

Initial cleanup of binders-related code

---

frontend/exporter/src/body.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs

Intermediate variants of MIR involve promoted constants, which are normal expressions turned into anonymous constants, which is a necessary step for cases like:
```rust
fn static_lifetime() -> &'static u32 {
let x = &0;
x
}
```
Hax crashes on them today (the call to `ucv.shrink()` panics); this PR fixes that.

Support other variants of MIR

---

frontend/exporter/src/types/copied.rs

I made a mistake in my last PR: evaluating constants eagerly is semantically incorrect. For example, this is valid rust:
```rust
pub trait HasLen {
const LEN: usize;
}
impl<const N: usize> HasLen for [bool; N] {
const LEN: usize = if true {
N
} else {
<Self as HasLen<N>>::LEN
};
}
```
but eagerly evaluating causes cycle errors. Promoted constants however should be evaluatable since they're only promoted when they're infallible.

Don't eval constants eagerly

---

engine/lib/import_thir.ml
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/mir_traits.rs

This PR makes it so trait solving never calls into `SInto`, as that was causing headaches with binders. There is still more work to do to clarify trait solving but that's less of a priority.

Detangle trait solving from `SInto`

---

proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Folds.fsti

In the loop body of `fold_enumerated_slice` I noticed that enumerate value is not equal to array element which is necessary for some use cases. An example of use case is here https://github.com/cryspen/libcrux/blob/dev-serialize/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cpa.fst#L218 where the enumerate value `re` has to be equal to the index element of `input` array.

Determine emuerate value by index

---

engine/backends/fstar/fstar_backend.ml
engine/lib/diagnostics.ml
engine/lib/phases/phase_rewrite_control_flow.ml
engine/lib/phases/phase_rewrite_control_flow.mli
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-ssprove.snap
tests/side-effects/src/lib.rs

Add RewriteControlFlow phase.

---

engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/features.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_reconstruct_question_marks.ml
engine/lib/phases/phase_simplify_question_marks.ml
engine/lib/print_rust.ml
engine/lib/print_rust.mli
engine/lib/subtype.ml
engine/utils/ppx_generate_features/ppx_generate_features.ml
test-harness/src/snapshots/toolchain__traits into-fstar.snap

I had leftover work while working on iterators.
Those were required for iterators at the time, and are good generally.
This PR:
- fixes the rust printer for projection predicates;
- derive compare and sexp for every type of the AST;
- add trait information on impl exprs

Add infos impl

---

frontend/exporter/src/state.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir_traits.rs
frontend/exporter/src/types/new/full_def.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This PR methodically cleans up trait resolution. It also tracks the index of locally-bound predicates for use in Charon. This solves many binder- and trait-resolution-related issues in Charon.

Cleanup trait resolution

---

engine/backends/fstar/fstar_backend.ml
engine/lib/attr_payloads.ml
engine/lib/phases/phase_and_mut_defsite.ml
engine/lib/phases/phase_functionalize_loops.ml
hax-types/src/diagnostics/mod.rs

Following #932, this PR adds issue id to basically all other errors in the engine.
Fix #921

chore: assign an issue id for every error in the engine

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/generic_printer/generic_printer.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_drop_references.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
frontend/exporter/src/types/copied.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

This PR disable default parameters on traits, both in the engine and in the exporter, following the conversation in #310.
Explanation (quoting my comment in code):
> On use site, Rust always give us all the generic
> parameters, no matter the defaultness. This information is
> thus not so useful. At the same time, as discussed in
> https://github.com/hacspec/hax/issues/310, extracting this
> default type causes failures when querying Rust for trait
> resolution. We thus decided to disable this feature. If
> this default type information is useful to you, please
> open an issue on https://github.com/hacspec/hax.
Fixes #310

fix(exporter+engine): drop default parameters on traits

---

Cargo.lock
engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__unsafe into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/unsafe/Cargo.toml
tests/unsafe/src/lib.rs

This PR follows from
https://github.com/hacspec/hax/issues/417#issuecomment-2387860612, and from PR #867.
It turns on the `unsafe` feature for the F* backend.

feat(engine/f*): allow unsafe code

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/easycrypt/easycrypt_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/backends/proverif/proverif_backend.ml
engine/bin/lib.ml
engine/lib/backend.ml
engine/lib/dependencies.ml
engine/lib/dependencies.mli
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/cyclic-modules/Cargo.toml
tests/cyclic-modules/src/lib.rs

Closes #396 
The idea is to put together objects that create a cyclic dependency at the module level. We bundle them in a newly created module (one for each cycle) and then use https://github.com/FStarLang/FStar/pull/3369 to selectively include these objects in the module they actually belong to.
List of changes compared to the existing implementation (that was present in `dependencies.ml` but not used by any backend):
- we solve name clashes in the bundles (by adding a hash to the names that clash)
- we replace the `let` and `type` keywords by `and` for mutually recursive items
- we replace the `unfold let` by `include` to make use of https://github.com/FStarLang/FStar/pull/3369
- we bundle not only mutually recursive items but also items that create a cyclic dependency without being …

Handle cyclic module dependencies

---

engine/backends/fstar/fstar_backend.ml

Thus this PR removes the unimplemented error in favor of an assertion failure.

fix(engine/f*): convert an unimplemented to an assertion failure

---

flake.nix

Add a script that checks the coherency between issues labeled `marked-unimplemented` on GitHub and issues mentionned in the engine in the `Unimplemented {issue_id: ...}` errors.

feat(nix/utils): intro. `check-unimlemented-issue-coherency`

---

cli/driver/src/driver.rs
cli/driver/src/exporter.rs
cli/driver/src/features.rs
cli/subcommands/src/cargo_hax.rs
engine/utils/phase-debug-webapp/src/lib.rs
frontend/exporter/options/src/lib.rs
frontend/exporter/src/body.rs
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/index_vec.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/sinto.rs
frontend/exporter/src/state.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/new/item_attributes.rs
frontend/exporter/src/types/serialize_int.rs
frontend/exporter/src/utils.rs
hax-lib-macros/src/lib.rs
hax-lib-macros/src/quote.rs
hax-lib-macros/src/rewrite_self.rs
hax-lib-macros/src/syn_ext.rs
hax-lib-macros/src/utils.rs
hax-lib-protocol-macros/src/lib.rs

This PR runs `cargo clippy --fix` on the code base, and then fixes a few things related to that.
Fixes #407

Run `cargo clippy --fix`

---

engine/lib/dependencies.ml

Fixes a regression introduced by #935  (see https://github.com/cryspen/libcrux/actions/runs/11153943502/job/31002385466).
That was caused by trying to rename a variant of a struct, but only enum variants should be renamed.

Ignore structs in variants renaming for bundling.

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/types/mir_traits.rs
frontend/exporter/src/types/new/full_def.rs

There are some contexts where normalization can fail (particularly type aliases), which causes a compiler panic.

Prefer `try_normalize_erasing_regions`

---

cli/driver/src/exporter.rs
cli/subcommands/src/cargo_hax.rs
frontend/exporter/src/comments.rs
frontend/exporter/src/lib.rs
hax-types/src/driver_api.rs
hax-types/src/engine_api.rs

This commit adds support for regular comments in hax. Comments are dumped with the command `cargo hax json -E -o -`.
To parse comments, this commit uses `rustc_lexer`, so the parsing is very dumb yet very reliable.
Fixes #951

feat(frontend): collect regular comments

---

CONTRIBUTING.md

This PR adds a regression policy in the `contributing.md`.

feat(contributing): add a `regressions` section

---

frontend/exporter/src/traits.rs

This reworks trait resolution as discussed offline: we only explore item bounds insofar as the `Self` type of the searched predicate is itself an associated type. This makes the search bounded, and makes it possible to support GATs in trait resolution.

Rework trait resolution to support GATs

---

engine/lib/ast_destruct.ml
engine/lib/ast_utils.ml
engine/lib/dune
engine/lib/phases/phase_reconstruct_asserts.ml
engine/lib/utils.ml
engine/utils/generate_from_ast/codegen_ast_builder.ml
engine/utils/generate_from_ast/codegen_ast_destruct.ml
engine/utils/generate_from_ast/generate_from_ast.ml

This PR adds an `ast_destruct` module to destruct ASTs nicely.
This PR also rewrites one phase that had a very verbose pattern matching to show off a bit how useful this can be to preserve our sanity while matching on syntax.
Fixes #941

feat(engine): add `ast_destruct` module

---

cli/subcommands/src/cargo_hax.rs
engine/backends/fstar/fstar_backend.ml
engine/backends/fstar/fstar_backend.mli
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
hax-types/src/cli_options/extension.rs
hax-types/src/cli_options/mod.rs
hax-types/src/diagnostics/message.rs
hax-types/src/engine_api.rs

The CLI is defined with the rust library clap. This PR introduce a
trait `Extension` which define an associated type per type of
`cli_options`.
For now, not all the types have been added to that trait: let's do
that lazily.
With this PR, it is easy to define a superset of hax' CLI.

Make options extensible

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__naming into-fstar.snap

The engine was dropping trait information when importing constants: now, if a constant `T::CONST` is an associated item of a non-inherent trait, we represent it `T::CONST` as a call to `CONST()` with the implementation expression for `T`.
Note that, in the engine, constants are already represented as functions of arity zero. Rust functions of arity zero are represented as functions that take exactly one `unit` input.
Fixes #840.

fix(engine): make consts fun. calls of arity 0 when there is an impl expr

---

frontend/exporter/src/traits.rs
frontend/exporter/src/types/copied.rs

Now that we thoroughly erase lifetimes in trait resolution, we shouldn't have any binder problems left.
Fixes https://github.com/hacspec/hax/issues/747

Remove workaround in trait resolution for associated items

---

engine/lib/concrete_ident/concrete_ident.ml
engine/lib/import_thir.ml
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/types/copied.rs

Fixes #997.
I have a meeting but then I'll push related changes in Charon.

Exporter get variant information works on unions

---

cli/driver/src/callbacks_wrapper.rs
cli/subcommands/build.rs
cli/subcommands/src/cargo_hax.rs
hax-types/build.rs
hax-types/src/cli_options/mod.rs
hax-types/src/lib.rs
justfile

This PR:
- Improve `cargo hax -V` and `cargo hax --version`:
Versions were broken: `cargo hax -V` was displaying the latest tag attached to the commit. So newer commits on main were tagged `v0.1.0-alpha`.
Also, if hax is built without git, the version was empty. Now we use `CARGO_PKG_VERSION` as a fallback.
cc @maximebuyse, you should get commit information from `cargo hax --version`, not `cargo hax -V`.
- fixes #801

feat(cli): better version information

---

frontend/exporter/src/traits/resolution.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

Fixes https://github.com/hacspec/hax/issues/684 by fully revealing opaque types during trait resolution.

Support `impl Trait` in trait resolution

---

engine/lib/ast_utils.ml

fix(engine): also rename concrete idents within a projector.

---

proof-libs/fstar/core/Core.Iter.Traits.Iterator.fst
proof-libs/fstar/core/Core.Iter.fsti
proof-libs/fstar/core/Core.Ops.Range.fsti
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Monomorphized_update_at.fst

The iterator model in the hax proof-libs used F* options instead of `Core.Option.t_Option`. This PR fixes that.
There is also a drive by fix remove the duplicate definition of `update_at_usize`

some fixes for iterators.f_next and update_at_usize

---

engine/backends/fstar/fstar_backend.ml
engine/backends/proverif/proverif_backend.ml
engine/lib/ast.ml
engine/lib/ast_utils.ml
engine/lib/deprecated_generic_printer/deprecated_generic_printer.ml
engine/lib/generic_printer/generic_printer_template.ml
engine/lib/phases/phase_transform_hax_lib_inline.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
engine/utils/generate_from_ast/codegen_visitor.ml

This PR adds a field `origin` to the constructor `Quote` for items.
This adds context when we use replace/before/after: backends now know where a quote comes from.

Quote items track replace

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/traits/resolution.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/thir.rs
frontend/exporter/src/types/ty.rs
frontend/exporter/src/utils.rs

This continues my work in cleaning up trait resolution. Of particular importance is the clarification of "required" vs "implied" predicates: required predicates must be proven to mention an item (e.g. one must prove `T: Sized` to mention `Option<T>`) whereas implied predicates are implied by the item being present in a signature (e.g. `T: Copy` implies `T: Clone`).
So far we consider all predicates on a trait declaration to be implied, but that's not what rustc does. For example:
```rust
trait Foo<T: Clone>: ToString {}
```
Here (according to rustc) `T: Clone` is required to mention `Foo`, and `Self: ToString` is implied by `Self: Foo`. I don't know if considering `T: Clone` as implied (like we implicitly did today) could cause problems but at least now what's happening is clear.

Improve trait resolution

---

engine/lib/dependencies.ml
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap

This avoids adding `include` statements in the generated f* with `DUMMY` idents (see #272)

Avoid bundling use items.

---

cli/subcommands/src/cargo_hax.rs
engine/lib/import_thir.ml
flake.lock
flake.nix
frontend/exporter/src/constant_utils.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/state.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/hir.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/thir.rs
frontend/exporter/src/types/ty.rs
hax-types/src/lib.rs
rust-toolchain.toml
test-harness/src/harness.rs

This upgrades our pinned toolchain toyesterday's nightly.

Upgrade rustc

---

hax-types/src/lib.rs

#1036 added an unconditional feature(rustc_private) on crate `hax-types`, but we need that to be non-nightly (this is consumed by other crates)!

fix: rustc_private

---

frontend/exporter/src/types/new/full_def.rs

`def_span` and `get_attrs_unchecked` panic on some foreign modules like `extern "rustc-call" { ... }` in `core`.

Avoid a panic in `FullDef`

---

frontend/exporter/src/types/thir.rs
test-harness/src/snapshots/toolchain__functions into-fstar.snap
tests/functions/Cargo.toml
tests/functions/src/lib.rs

We were missing the case where a function is not directly a function but a refrence (or nested references) to a function.

fix(exporter/thir): fix #1048

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/lib.rs

This commit:
- changes the representation of floats for constant literals, instead of storing raw bits with a u128, we store a string representation of the float;
- adds support for float in the function `scalar_int_to_constant_literal`
Note: this will require a change in Charon.

feat(frontend/consts): float lits: use strings not bits, more support

---

engine/lib/dependencies.ml
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap

fix(engine) Remove attributes on bundle aliases and filter out NotImplementedYet.

---

frontend/exporter/src/traits.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/ty.rs

Along with constness information, this is one of the last remaining queries we were doing in charon.

Add `ImplExpr` information to associated types in an impl block

---

frontend/exporter/src/state.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/ty.rs

This reworks the representation of associated impl items. The problem this solves is:
```rust
trait Trait {
type Type: Clone = i32;
}
impl Trait for () {}
```
Here the impl implicitly reuses the type provided by the trait. The version of the type that's virtually in the impl does not have a `DefId` however, which makes it hard to get information about it. This PR adds a representation for these defaulted items, and gathers the necessary information.
Now `FullDefKind::TraitImpl.items` always has the same number of entries (and in the same order) as `FullDefKind::Trait.items`.
There remains some work to do for methods because I don't yet handle that in charon. This is also unfortunately limited wrt GATs; we'd have to construct our own `ParamEnv`s to solve that properly so I'm leaving it as …

Include defaulted items in `FullDefKind::TraitImpl`

---

engine/lib/concrete_ident/concrete_ident.ml
engine/lib/import_thir.ml
engine/names/extract/build.rs
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
frontend/exporter/src/id_table.rs
frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/types/def_id.rs

This adds `DefId`s to the interning table, and lets a `DefId` store a pointer to its parent.
This is incomplete: I did not propagate the changes to the ocaml side.

Intern `DefId`s

---

.github/workflows/mlkem.yml

Fix ml-kem ci job.

---

.github/workflows/install_and_test.yml
.utils/rust-by-example.js
flake.lock
flake.nix

Fixes https://github.com/hacspec/hax/issues/540, but instead of trying two snippets, it's trying 157 snippets.
41 are not going though, on a total of 198: we have about 80% success rate here.
This needs #1090.

feat(ci): test rust by examples (extract to F*)

---

engine/lib/phases/phase_drop_return_break_continue.ml
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-ssprove.snap
tests/side-effects/src/lib.rs

Fixes #1089.
Closures were not treated in the elimination of `return`/`break`/`continue`.

fix(engine) Drop return/break/continue inside closures.

---

cli/subcommands/src/cargo_hax.rs
engine/bin/lib.ml
engine/lib/diagnostics.ml
engine/lib/import_thir.ml
engine/lib/print_rust.ml
engine/lib/span.ml
engine/lib/span.mli
engine/names/extract/build.rs
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
frontend/exporter/src/id_table.rs
hax-types/src/cli_options/mod.rs
hax-types/src/diagnostics/message.rs
hax-types/src/diagnostics/mod.rs
hax-types/src/engine_api.rs
test-harness/src/snapshots/toolchain__include-flag into-coq.snap

This PR:
- makes spans carry a hint about their parent item;
- makes errors carry a hint about which item the error comes from;
- adds a `--stats` flag to the verb `into`, printing information about how many items the engine was able to process and a total number of items.
This will be quite useful for mass testing the engine: we'll be able to have statistics about how many items in a crate we can translate.

feat(engine): keep track of parent items in spans

---

cli/subcommands/src/cargo_hax.rs
frontend/exporter/options/src/lib.rs
hax-types/src/cli_options/extension.rs
hax-types/src/cli_options/mod.rs

This is useful for the workbench.
This PR:
- adds a hidden option `cargo hax __json` that just consumes stdin and parse that as CLI options
- implements `ToString` for a few types
- make more fields public for types in cli_options

feat(frontend/cli): improve options

---

engine/backends/fstar/fstar_backend.ml
engine/lib/dependencies.ml
engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__interface-only into-fstar.snap
tests/cli/interface-only/src/lib.rs

Implements the action plan in #1113

feat(engine) Extract vals for trait impls in interface only mode.

---

cli/subcommands/src/cargo_hax.rs
engine/backends/coq/coq/coq_backend.ml
engine/lib/generic_printer/generic_printer.ml
engine/utils/sourcemaps/location.ml
engine/utils/sourcemaps/mappings/dual.ml
engine/utils/sourcemaps/mappings/instruction.ml
engine/utils/sourcemaps/mappings/mappings.ml
engine/utils/sourcemaps/mappings/mappings.mli
engine/utils/sourcemaps/mappings/types.ml
engine/utils/sourcemaps/source_maps.ml

This PR:
- makes cargo hax save source maps as files if the engine produce any
- fix a bug in the source map encoding
- output source maps for the Coq backend
To test the source maps for Coq:
- `cargo hax into coq` on a crate
- https://evanw.github.io/source-map-visualization/, upload one `.v` file and it's corresponding `.v.map` file (no need for the rust source files, they are embedded in sourcemaps)

Engine: source maps: fix bugs, add features, enable for Coq

---

examples/chacha20/proofs/fstar/extraction/Makefile
proof-libs/fstar/core/Alloc.Borrow.fst
proof-libs/fstar/core/Alloc.Boxed.fst
proof-libs/fstar/core/Alloc.Fmt.fsti
proof-libs/fstar/core/Alloc.String.fst
proof-libs/fstar/core/Alloc.Vec.fst
proof-libs/fstar/core/Core.Borrow.fsti
proof-libs/fstar/core/Core.Convert.fst
proof-libs/fstar/core/Core.Error.fsti
proof-libs/fstar/core/Core.Fmt.fsti
proof-libs/fstar/core/Core.Iter.Traits.Collect.fst
proof-libs/fstar/core/Core.Iter.Traits.Iterator.fst
proof-libs/fstar/core/Core.Marker.fst
proof-libs/fstar/core/Core.Ops.Bit.fsti
proof-libs/fstar/core/Core.Option.fst
proof-libs/fstar/core/Core.Result.fst
proof-libs/fstar/core/Std.Collections.Hash.Map.fsti
proof-libs/fstar/core/Std.Hash.Random.fsti
proof-libs/fstar/core/Std.Io.Error.fsti
proof-libs/fstar/core/Std.Io.fsti

Upstream fstar core changes from cryspen-sandwich.

---

engine/backends/fstar/fstar-surface-ast/FStar_Parser_ToDocument.ml
justfile
test-harness/src/snapshots/toolchain__literals into-coq.snap
test-harness/src/snapshots/toolchain__literals into-fstar.snap
tests/literals/src/lib.rs

This PR:
- Fixes issue #993
- Adds a test
- Improve the justfile recipes related to testing

Engine: F*: fix `\0`

---

proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti

This PR restores `neg_equiv_lemma` which is needed for portable compress proofs in this PR https://github.com/cryspen/libcrux/pull/631.

Restore neg_equiv_lemma

---

book/src/SUMMARY.md
book/src/contributing/architecture.md

This PR adds a page to the book, documenting the high-level architecture of hax.
Fixes #752

doc(book): architecture of hax

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__literals into-fstar.snap
test-harness/src/snapshots/toolchain__patterns into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/patterns/Cargo.toml
tests/patterns/src/lib.rs

Fixes #1170 
This mostly ignores type ascription patterns in the F* backend (maybe we should completely ignore them, see https://github.com/hacspec/hax/issues/1170#issuecomment-2527433453). These patterns are translated as their subpattern. This fixes the issue from #1170 
The main difference as a side effect is that for 
```
let _: i8 = 1 + 1;
```
We will now generate
```
let _:i8 = 1y +! 1y in
```
instead of 
```
let (_: i8):i8 = 1y +! 1y in
```
Both are valid F* and the new version is simpler, and clearer.

Remove rejected type ascription patterns from generated f*.

---

engine/lib/ast_utils.ml
test-harness/src/snapshots/toolchain__generics into-fstar.snap
tests/generics/src/lib.rs

Fixes #1176 .
See https://github.com/hacspec/hax/issues/1176#issuecomment-2536040766 for details.

fix(engine) Fix generic type constraints naming bug.

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/attr_payloads.ml
engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__literals into-coq.snap
test-harness/src/snapshots/toolchain__literals into-fstar.snap

Fixes #1070 
Instead of just skipping generated impls, this adds the `Erased` attribute to them so that the body is dropped but they still exist in the engine. This allows for them to be moved by bundling thus removing the spurious `let open`.

Skip generated impls using `Erased` attribute.

---

engine/backends/fstar/fstar_backend.ml
engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__attribute-opaque into-fstar.snap

Fixes #1131. Fixes #1152.
This is a followup of #1134. It fixes 2 problems:
- `const`s inside (non-trait) impls are not erased by type-only flag (so that the behaviour is the same as for top-level `const`s)
- For erased `const`s (when an `opaque` flag is added by the user) we now produce a `val` in the `fsti` (it was missing before).

fix(engine) Opaque consts

---

PUBLISHING.md

This PR just document the fact we should not create or push tags before merging a release PR, that should come after merging a release PR.

feat(publishing): use `--no-tag`

---

hax-types/Cargo.toml

You can not publish a crate with a wildecard as version number.
I published all the crates. You need to move all the tags to this commit when merged.
I published with
```
cargo release -p hax-frontend-exporter-options -p hax-adt-into -p hax-frontend-exporter -p hax-types -p hax-subcommands -p cargo-hax -p hax-export-json-schemas -p hax-pretty-print-diagnostics -p hax-lib-macros-types -p hax-lib-macros -p hax-lib -p hax-driver --no-tag --execute
```

hax-types: version for serde-brief

---

flake.nix
frontend/exporter/src/types/def_id.rs
frontend/exporter/src/types/hir.rs
frontend/exporter/src/types/span.rs

This PR fixes [#1162](https://github.com/hacspec/hax/issues/1162): it is adding a `DefKind` on `DefIdContents`.

Frontend/exporter: Add a `kind` field to `DefIdContents`

---

cli/driver/src/exporter.rs
cli/subcommands/build.rs
cli/subcommands/src/cargo_hax.rs
engine/backends/fstar/fstar_backend.ml
engine/bin/lib.ml
engine/lib/ast_builder.ml
engine/lib/ast_utils.ml
engine/lib/attr_payloads.ml
engine/lib/dependencies.ml
engine/lib/hax_io.ml
engine/lib/import_thir.ml
engine/lib/phases/phase_cf_into_monads.ml
engine/lib/phases/phase_hoist_disjunctive_patterns.ml
engine/lib/phases/phase_transform_hax_lib_inline.ml
engine/names/extract/build.rs
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
flake.nix
hax-types/src/diagnostics/mod.rs
hax-types/src/driver_api.rs
hax-types/src/engine_api.rs

This PR:
- adds a version to `haxmeta` files
- adds a version to the engine
- makes the frontend check haxmeta versions
- makes the engine check the frontend version
- improve parsing error reporting
- makes generated parsers conform to yojson style
- report parsing errors in the F* backend
- removes most of `*_exn` calls
- removes most of failwith calls
Fixes https://github.com/hacspec/hax/issues/1150, fixes https://github.com/hacspec/hax/issues/1188, fixes #1187
Context: this PR goes toward better user experience for releasing hax v0.1, it gets rid of most of remaining unhandled explicit failures

Engine: get rid of most of exception throwing function calls, improve parsers and error reports

---

engine/lib/ast_utils.ml
engine/lib/dependencies.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap

Fixes #1016 
When creating the dependency graph, we were looking for associated items in the attributes of the item. But associated items can also be held by attributes of subparts of the item (like variants in the case of a struct).

fix(engine) Check attributes of descendants to build dependency graph.

---

engine/backends/fstar/fstar_backend.ml

Fixes #1202.
This avoids creating an fst file with only comments in it in fsti-only mode. The filtering of `Impl` elements is moved to after treating comments.

fix(backend) Filter Impl after adding comments.

---

engine/lib/concrete_ident/concrete_ident.ml
engine/lib/concrete_ident/concrete_ident.mli
engine/lib/dependencies.ml
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap

This PR:
- Closes #1200. Makes bundle names stable, by computing the hash based on the names of the modules going inside the bundle (instead of the items)
- Fixes #1157. By adding a disambiguator when names clash, instead of modifying the last string in the path (which fails for impls that don't have a string at the en of their paths)

Bundle naming fixes

---

engine/lib/ast_utils.ml
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap
test-harness/src/snapshots/toolchain__enum-repr into-fstar.snap
test-harness/src/snapshots/toolchain__guards into-fstar.snap
test-harness/src/snapshots/toolchain__let-else into-fstar.snap
test-harness/src/snapshots/toolchain__literals into-fstar.snap
test-harness/src/snapshots/toolchain__loops into-fstar.snap
test-harness/src/snapshots/toolchain__pattern-or into-fstar.snap
test-harness/src/snapshots/toolchain__patterns into-fstar.snap
test-harness/src/snapshots/toolchain__reordering into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap
test-harness/src/snapshots/toolchain__unsafe into-fstar.snap

Fixes #1207 
This adds an ascription to pattern matching scrutinees. Maybe this could be made more fine-grained to do it only with scrutinees that can cause issues (this would avoid making the generated code too verbose)

fix(engine) Add ascription to match scrutinees.

---

.github/workflows/mlkem.yml

This PR updates the F* version used by the ML-KEM CI job. The job was failing recently (see for example https://github.com/hacspec/hax/actions/runs/12482298578/job/34836176279, because of a syntax error). Using a more recent F* fixes this (https://github.com/hacspec/hax/actions/runs/12483217088/job/34838637301)

fix(CI) Update F* version to fix mlkem CI job 

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/lib/ast.ml
engine/lib/deprecated_generic_printer/deprecated_generic_printer.ml
engine/lib/generic_printer/generic_printer.ml
engine/lib/generic_printer/generic_printer_template.ml
engine/lib/phases/phase_transform_hax_lib_inline.ml
engine/lib/print_rust.ml
engine/lib/subtype.ml
engine/utils/generate_from_ast/codegen_printer.ml
engine/utils/generate_from_ast/codegen_visitor.ml
test-harness/src/snapshots/toolchain__loops into-fstar.snap

Fixes #1196 
The investigation for #1196 revealed that subparts of `Quote` variant in the AST were ignored by visitors. The easiest way to change that is to use a `quote_contents` ADT inside instead of an inlined polymorphic variants. This involves quite a few changes here and there.

fix(engine) Make sub-parts of `Quote` visited by visitors

---

README.md

This PR changes slightly the README to reflect the state of https://github.com/hacspec/hax/issues/417: unsafe blocks are handled for some time already.
I noticed that while writting release notes.

Update README.md: `unsafe` is OK to use

---

engine/lib/import_thir.ml
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/ty.rs
test-harness/src/snapshots/toolchain__attribute-opaque into-fstar.snap
test-harness/src/snapshots/toolchain__traits into-fstar.snap

I've started checking for consistency of generics in charon, which revealed several inconsistencies in how we deal with function generics and function calls (mostly related to late-bound lifetime variables). This PR fixes a number of these issues.&

Fix generics handling for function calls

---

engine/lib/ast_utils.ml
test-harness/src/snapshots/toolchain__traits into-fstar.snap
tests/traits/src/lib.rs

Fixes #1218.
The bug happens when an impl expr is contained inside the trait goal as trait goals are not visited by the visitor. The fix is simply to visit trait goals with the visitor so that impl expr renaming also happens there.

Visit trait goals to rename impl expr they may contain.

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__naming into-fstar.snap

fix(engine) Add type arguments for associated constants.

---

engine/lib/phases/phase_and_mut_defsite.ml
engine/lib/side_effect_utils.ml
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-ssprove.snap
tests/side-effects/src/lib.rs

Fixes #1175 
The bug is due to the visitor rewriting `returns` in `AndMutDefSite` not rewriting the expressions inside returns. In the reproducer there is a `?` inside a `return` (so a `return` inside a `return`). Not visiting it was triggering the crash because several `returns` of the same function had different return types.

fix(engine) Propagate return rewrite to avoid crash in side_effect_utils

---

engine/lib/phases/phase_and_mut_defsite.ml
engine/lib/phases/phase_local_mutation.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
test-harness/src/snapshots/toolchain__loops into-fstar.snap
tests/loops/src/lib.rs

This is an attempt to make things better for #720.
As far as we know, this bug happens when there is a loop with side effects at the end of a function. Then `AndMutDefSite` transforms this to:
```
let hax_temp_output: tuple0 = <loop>
hax_temp_output
```
And `LocalMutation` transforms this binding to:
```
let Tuple2(modified_var, hax_temp_output) = <loop>
...
```
but the transformation of the loop is made in such a way that here `<loop>` has the type of <modified_var>.
This fix is modifying `AndMutDefSite` so that if the expression has type unit, instead of the previous binding it produces:
```
let _ = <loop>
()
```
This works better with the assumptions of `LocalMutation` and fixes the bug (at least for the last reproducer that I added as a test). A more in depth rework of both those …

fix(engine) Attempt to fix double return bug.

---

frontend/exporter/src/traits.rs
frontend/exporter/src/traits/resolution.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/new/full_def.rs

This concludes the work I started a while ago to clarify the predicates used for trait solving each item: the single source of truth is now `require_predicates`/`implied_predicates`. This made it possible to exclude some unnecessary derived predicates in the `implied_predicates` of associated types, which was a long-standing TODO.

Make predicate handling a bit more consistent

---

frontend/exporter/src/types/mir.rs

We always translate parent clauses before child clauses except in this one place. This caused us to emit inconcistent generics.

Fix order of `Call` trait clauses

---

engine/lib/import_thir.ml
frontend/exporter/src/traits.rs
frontend/exporter/src/traits/resolution.rs
test-harness/src/snapshots/toolchain__traits into-fstar.snap

This adds some info to `ImplExpr` that I need to handle associated types properly.

Add more info to `ImplExprAtom::Builtin`

---

CHANGELOG.md
CONTRIBUTING.md
PUBLISHING.md

This PR adds a changelog: I forgot to init it in #1245...
This PR also documents the workflow related to the changelog in CONTRIBUTING and in PUBLISHING.

changelog: initialize

---

README.md
docs/index.md
docs/manual/index.md
docs/publications.md

@W95Psp there's more for developer documentation in the readme that's not on the docs yet. How about moving all of that to the dev docs?
There's a little duplication now in the readme and the website. We could solve that by reducing the amount of information in the readme (it's a bit much) and move some of it purely to the website.
@karthikbhargavan when the vstte paper is up, this should be added to the list of publications too.

updatge readme and docs

---

.github/workflows/test_installs.yml
hax-lib/macros/src/utils.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/Cargo.lock
tests/attributes/src/lib.rs

This PR fixes #1266.
Consider the following Rust:
```rust
#[hax_lib::attributes]
trait T {
#[hax_lib::ensures(|_|true)]
fn v(x: &mut Self);
}
```
The `ensures` clause was expanded (running `just expand` within hax repo, on the test crate) as:
```rust
fn ensures<Self_>(x: &Self_, (x_future): (&Self)) -> bool
where
Self_:,
{
true
}
```
The issue here is that we extract the various `&mut` arguments before renaming `Self` into `Self_`.
This PR fixes that, now the Rust expansion is:
```rust
fn ensures<Self_>(x: &Self_, (x_future): (&Self_)) -> bool
where
Self_:,
{
true
}
```

fix(hax-lib/macros): handle correctly `&mut Self` arguments in `ensures`

---

engine/backends/fstar/fstar_backend.ml
engine/hax-engine.opam
engine/hax-engine.opam.template
engine/lib/dependencies.ml
engine/lib/dependencies.mli
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap
tests/cyclic-modules/src/lib.rs

Move trait methods in cyclic dependencies bundling.

---

docs/javascripts/hax_playground.js
docs/overrides/main.html
docs/stylesheets/hax_playground.css

This PR:
- re-installs editors on JS naviation
- uses codemirror instead of ace (ace editors were messed up after re-installs)
- formats properly the results
Fixes https://github.com/cryspen/hax/issues/1226

fix(mkdocs): use codemirror instead of ace, re-setup on page reload

---

.github/workflows/bertie.yml
.github/workflows/engine_js_build.yml
.github/workflows/gh_pages.yml
.github/workflows/install_and_test.yml
.github/workflows/mlkem.yml
.github/workflows/release.yml

https://determinate.systems/posts/magic-nix-cache-free-tier-eol/
This PR just runs `sd '.*DeterminateSystems/magic-nix-cache-action@main\n+' '' .github/**/*`

ci(gha): drop magic-nix-cache action because of EOL

---

engine/lib/concrete_ident/concrete_ident.ml

This removes an `exn` function to avoid potential crashes.

fix(engine) Add default case for disambiguation of bundle element names

---

.github/workflows/engine_js_build.yml
.github/workflows/format.yml
.github/workflows/install_and_test.yml
.github/workflows/licenses.yml
.github/workflows/release.yml
.github/workflows/test_installs.yml
dependabot.yml

This PR:
- [bump actions/checkout from v3 to v4](https://github.com/cryspen/hax/commit/69a2f8f0fdf3ef13ee4dbea5b2e5c30622afe70c)
- [enable gha alerts in dependabot]https://github.com/cryspen/hax/commit/e77c439ad7e4bb8b3b792a19a4d905a732322311)
Fixes #1107

Update CI dependencies

---

engine/backends/coq/coq/coq_backend.ml
engine/lib/ast.ml
engine/lib/generic_printer/generic_printer_template.ml
engine/utils/generate_from_ast/codegen_visitor.ml
engine/utils/generate_from_ast/generate_from_ast.ml

Fixes https://github.com/cryspen/hax/issues/1177
The crash was due to the `item_ident` of `item_quote_origin` (inside `Quote` items) not being renamed when a bundle is created. This is apparently a weird bug of the visitor (I would expect `visit_concrete_ident` to be called on this name without having to override `visit_item_quote_origin`).

fix(engine) Make sure origins are renamed in bundles.

---

engine/lib/dependencies.ml
proof-libs/fstar/core/Core.Core_arch.X86.Pclmulqdq.fsti
proof-libs/fstar/core/Core.Core_arch.X86.Sse2.fsti
proof-libs/fstar/core/Core.Core_arch.X86.fsti
proof-libs/fstar/core/Core.Core_arch.X86_64_.Sse2.fsti
test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap

Fixes #1283 and more small regressions from #1199.
One of the fixes should be temporary, I opened https://github.com/cryspen/hax/issues/1285 to track this.

fix(engine) Fix naming bundle regression

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__enum-repr into-coq.snap
test-harness/src/snapshots/toolchain__enum-repr into-fstar.snap
test-harness/src/snapshots/toolchain__enum-repr into-ssprove.snap
tests/enum-repr/src/lib.rs

This PR fixes #881.
I understood `Relative` in https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/enum.VariantDiscr.html as "relative to the previous repr", while it is relative to the last explicit repr.
This PR simplifies a bit the chunk of code (the correct logic is simpler than what was implemented before)

Engine: fix implicit representation for enums

---

docs/javascripts/hax_playground.js

This PR makes the snippets in the manual use the latest checkout of main available of hax in the integration of the playground

feat(manual): hax-playground integration: use latest `main`

---

engine/lib/side_effect_utils.ml
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-ssprove.snap
tests/side-effects/src/lib.rs

Fixes #1300 
The problem is that returns inside closures only break the control flow of the closure and not of the outter function.

fix(engine) Fix return inside closure.

---

engine/lib/phases/phase_drop_return_break_continue.ml
test-harness/src/snapshots/toolchain__loops into-fstar.snap
tests/loops/src/lib.rs

Fixes #1288.
In loops that have only `continue` and no `return`/`break` we don't need to wrap the `continue` value in a `ControlFlow` type. This was already expected and hax produced the right type for the loop but still wrapped the value. This PR fixes this to so that the `continue` statement is replaced by just the value of the accumulator.

fix(engine) Fix loops with `continue` and no `return`/`break`

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__generics into-fstar.snap
tests/generics/src/lib.rs

Fixes #1289.
@W95Psp The changes fix the bug but feel a bit ad hoc, if you see some other cases of `NamedConst` which need an `App` with `args` or `generic_args` we can try to catch them as well.

fix(engine) Add const parameter for assoc const of parametric impl.

---

engine/lib/ast_utils.ml
engine/lib/phases/phase_simplify_question_marks.ml
test-harness/src/snapshots/toolchain__side-effects into-fstar.snap
test-harness/src/snapshots/toolchain__side-effects into-ssprove.snap
tests/side-effects/src/lib.rs

Fixes #1299 
The problem is that in this case we have a match branch:
```
core::ops::control_flow::ControlFlow_Continue(val) => {
&(deref(val))
}
```
and the phase expects the usual:
```
core::ops::control_flow::ControlFlow_Continue(val) => {
val
}
```
I tried moving `Simplify_question_marks` after `Drop_references`, but this means moving it after `Direct_and_mut` which also messes with the pattern needed to be recognized for question marks...

fix(engine) Fix question marks simplification with deref/borrow.

---

frontend/exporter/src/rustc_utils.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/ty.rs

Since they always come together, grouping them makes things a bit more consistent. In fact we were getting confused about GAT predicates, which this clarifies.

full_def: group generic and predicates into a common struct

---

frontend/exporter/src/constant_utils.rs

This fixes an ICE on promoted MIR with some non-trivial constants (the `try_destructure_mir_constant_for_user_output` method panics for some values of `ty.kind()`).

Avoid an ICE by matching on type earlier

---

engine/lib/import_thir.ml
frontend/exporter/src/constant_utils.rs

We incorrectly fell back to `ByteStr` for evaluated constants but that's unfortunately wildly incorrect: with promoted_mir, most constants end up of that form. This just adds a new variant to catch this case.
Charon breakage is expected and fine since we're adding a variant.

 Not all evaluated MIR constants are byte strings

---

proof-libs/fstar/core/Rand_core.fsti

CryptoRng implementations must implement RngCore.
CryptoRngCore implementations must implement CryptoRng.

Proof libs (F*): fix trait inheritance in rand-core

---

docs/blog/.authors.yml

Feel free to use a different description. But without a description it doesn't build.
We also need to file an issue that we apparently don't build the docs on CI and hence didn't notice that this failed.

mkdocs: add Maxime description

---

setup.sh

Since rustup 1.28, toolchains don't get installed automatically.
See https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html

fix(setup.sh): rustup 1.28

---

cli/default.nix
flake.nix

This PR fixes an issue of nix-built hax on darwin.
Some library were not resolved correctly.
Thanks Sebastian Ertel who raised the issue on the zulip (see https://hacspec.zulipchat.com/#narrow/channel/269544-general/topic/Hax.20on.20darwin).

fix(nix): MacOS: add rustc and libz dylib to `DYLD_LIBRARY_PATH`

---

.github/workflows/mlkem.yml

This PR uses cachix to get prebuilt F* binaries.

ci(nix): use F* bin cache in mlkem.yml

---

engine/backends/coq/coq/coq_backend.ml
engine/lib/generic_printer/generic_printer.ml
engine/lib/generic_printer/generic_printer_template.ml

This PR changes the method of the generic printer `item'_Type_struct` so that it now takes two arguments `type_name` and `constructor_name`, instead of only one `name`.
That latter `name` was the type name. Now we also pass explicitely a constructor name.
The constructor and type name for a struct are different, although rendered in the same way in some backends. The rendering depends on the name policy chosen by the backend.

fix(engine/gen-printer): fixes #1294

---

engine/lib/concrete_ident/concrete_ident.ml
engine/lib/concrete_ident/concrete_ident_render_sig.ml

This commit allows for a better control over name rendering.
This is useful for PR #1108.

feat(engine/names): extend name policy expressivity

---

engine/backends/fstar/fstar_backend.ml
engine/names/src/lib.rs
hax-lib/macros/src/dummy.rs
hax-lib/macros/src/implementation.rs
hax-lib/macros/src/utils.rs
hax-lib/src/implementation.rs
hax-lib/src/proc_macros.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR adds support for `#[hax_lib::decreases(e)]` in hax-lib and in the F* backend.
Most of the code was already there.
In `#[hax_lib::decreases(e)]`, `e` can be of any type.
Fixes https://github.com/cryspen/hax/issues/1233

feat(hax-lib): add support for `decreases` clauses in F*

---

engine/lib/import_thir.ml
test-harness/src/snapshots/toolchain__statics into-fstar.snap
tests/Cargo.lock
tests/Cargo.toml
tests/statics/Cargo.toml
tests/statics/src/lib.rs

This PR:
- reject explicitly mutable static items
- reject explicitly asm blocks
- imports static items (as constants, essentially). This is OK since hax cannot hanlde interior mutability anyway. Pure static items behave just as constants.
Fixes #1240
Fixes #1127

Engine: import static items (but mutable ones), reject asm blocks

---

engine/backends/fstar/fstar_backend.ml
hax-lib/macros/Cargo.toml
hax-lib/macros/src/utils.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

fix(engine/F*): `self_` -> `self` for clauses of methods
Consider the following piece of code:
```rust
struct S(pub  u8);
impl S {
#[hax_lib::requires(self.0 == 0)]
fn f(&self) {}
}
```
The `requires` annotation produces a standalone function that looks like the following:
```rust
fn requires(self_: S) -> bool {
self_.0 == 0
}
```
Here, we can't use `self`: this is a reserved keyword in Rust, and we are not in a `impl` context.
Thus, the macro renames `self` into `self_`.
The bug described in #1276 comes from this renaming not being reverted in the engine.
With this commit, when the F* backend inteprets
such clauses, if the function on which a clause
exists have a `self` as first argument, we now
substitute the first argument of the clause
function to replace it with the first argument of …

fix(engine/fstar backend): subst self_ to self

---

engine/backends/fstar/fstar_backend.ml
test-harness/src/snapshots/toolchain__attributes into-fstar.snap

This commit drops preconditions on lemmas, so that lemmas are always of the form `Lemma (phi)`.
Fixes #820

fix(engine/fstar-backend): drop spurious precondition on `Lemma`s

---

hax-lib/src/dummy.rs

The dummy implementation of hax-lib was missing a `int!` macro. This commit adds such a (trivial) macro.

fix(hax-lib/dummy): intro `int!`

---

hax-lib/src/prop.rs

This PR makes `Prop::eq` to work not only on `Prop`s, but on any type: any time should be comparable in `Prop`.

hax-lib: prop: allow equality on every type

---

engine/lib/phases/phase_specialize.ml
hax-lib/macros/src/implementation.rs
hax-lib/src/implementation.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR makes the following work:
```rust
fn props() {
hax_lib::assume!(hax_lib::fstar::prop!("True"));
hax_lib::assert_prop!(hax_lib::fstar::prop!("True"));
}
```

fix(hax-lib/assume): fixes assume and assert_prop

---

hax-lib/macros/src/rewrite_self.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This commit allows us to write:
```rust
struct Dummy;
impl Dummy {
#[hax_lib::ensures(|_| future(self) == self)]
fn f(&mut self) {}
}
```
`RewriteSelf` was not taking into account the mutability or lifetime of `self` in function signature: this commit fixes that.

fix(hax-lib): allow `future(self)`

---

.github/workflows/flake_lock.yml
flake.lock

PR #1361 updated flake.nix but not flake.lock, this yields an error in the playground.
This PR fixes the playground.
This PR also adds a CI job that checks for the lockfile to be up to date.

fix: update flake.lock

---

engine/backends/fstar/fstar_backend.ml
hax-lib/Cargo.toml
hax-lib/proofs/fstar/extraction/Hax_lib.Int.fst
hax-lib/src/dummy.rs
hax-lib/src/int/bigint.rs
hax-lib/src/int/mod.rs
proof-libs/fstar/core/Core.Num.fsti
tests/Cargo.lock

This PR:
- fix `BigInt::new`
- add `overflowing_sub` F* model for u64
- derives display for Int
- add F* defintion for `Int::pow2`
- adapt names (because of rework naming PR)
- add `rem_euclid` for Int

`hax-lib`: `Int` improvements and fixes

---

frontend/exporter/src/traits.rs
frontend/exporter/src/types/ty.rs

Closures inherit the predicates from their parent items, yet when solving these predicates we only took the first parent. This caused issues for closures inside impls and likely for closures inside closures.
Fixes https://github.com/AeneasVerif/charon/issues/627.

Correctly handle impl exprs for closures

---

Cargo.lock
hax-lib-protocol-macros/Cargo.toml
hax-lib-protocol-macros/src/lib.rs
hax-lib/macros/Cargo.toml
hax-lib/macros/src/implementation.rs
tests/Cargo.lock

Fixes #1369, this replaces proc-macro-error by [proc-macro-error2](https://github.com/GnomedDev/proc-macro-error-2) which is a maintained fork.

Switch to proc-macro-error2 because original is unmaintained.

---

engine/lib/import_thir.ml

Fixes #1370 
To elaborate on what was discussed in the issue, the AST printing happens only when the error is produced in `import_thir`. When the error is produced later, we have some pretty-printed Rust, which can be nice and should be compact enough to have no performance issue. So I think it makes sense to drop only the raw ASTs. I replaced it by an empty string, not sure if instead we can have something compact but useful out of a `Thir.decorated_for__expr_kind`.

Remove AST printing in import_thir errors.

---

engine/lib/ast_utils.ml

This is a followup on #1388 
Seems like even pretty printed ASTs that result from errors in the different phases can get big. This was the case in the problem described by https://github.com/cryspen/hax/issues/1370#issuecomment-2769380136.
So we should also cut them to avoid big performance issues in the F* backend. I also added something to remove consecutive whitespaces. Indeed, the pretty-printed rust is formatted with indentation but placed in a string where new lines appear as `\n` so these consecutive whitespaces just make it harder to read.

Cut ASTs printed in errors when they are too long.

---

cli/default.nix

Recent versions of crane scrape references to the rust toolchain in the compiled output, but we need them for dynamic linking. This opts out of that behavior.

Tell crane to keep references to the rust toolchain

---

engine/backends/proverif/proverif_backend.ml

This is an admittedly dodgy workaround for https://github.com/cryspen/hax/issues/1400, in that we force each match arm's body to have the type of the first match arm body. This is correct, since there are no empty matches and they must have the same type.
It doesn't address the PV backend's lacking treatment of and Option, Result.
Fixes https://github.com/cryspen/hax/issues/1400

[ProVerif] Match arm type error workaround

---

justfile

This commit adds a `+nightly` so that `just expand` works even if the default toolchain is not nightly. This can be useful when using this justfile outside of hax' worktree.

feat(justfile): `just expand`: always use nightly

---

proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti

This commit adds a lemma that rewrites `x as T as U` into `x` when `x` as type `T` and that `U` is an integer type bigger than `T`.

feat(fstar/proof-libs): add a lemma for simplifying double casts

---

engine/lib/concrete_ident/concrete_ident.ml
test-harness/src/snapshots/toolchain__interface-only into-fstar.snap
test-harness/src/snapshots/toolchain__naming into-fstar.snap
tests/naming/src/lib.rs

Fixes #1411. The solution implemented here corresponds to what is described in https://github.com/cryspen/hax/issues/1411#issuecomment-2820386290

fix(engine) Fix name clashes for functions defined in impl methods.

---

proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti

Make `>>` unfoldable, but hide it to the SMT, to preserve the previous behavior when not normalizing.

fix(proof-libs): give a computable definition to `>>`

---

frontend/exporter/src/constant_utils/uneval.rs
frontend/exporter/src/types/mir.rs

Currently, hax frequently fails during constant evaluation -- in particular when closures are involved/when attempting to translate the std library. 
However, these constants are sometimes not needed in the end result: in our use case, we translate whole crates (std included) with [charon](https://github.com/AeneasVerif/charon), and symbolically execute the result; many of our tests fail, simply because hax panics on a constant that appears in a translated file, despite not being used. 
This PR gracefully falls back to `ConstantExprKind::Todo` on const evaluation failure or when hax doesn't know how to translate a constant; this allows the translation to progress, and for the end consumer to decide what to do with these.

Use `ConstantExprKind::Todo` more

---

engine/lib/phases/phase_functionalize_loops.ml
engine/names/src/lib.rs
hax-lib/macros/src/dummy.rs
hax-lib/macros/src/implementation.rs
hax-lib/src/dummy.rs
hax-lib/src/implementation.rs
hax-lib/src/proc_macros.rs
hax-lib/src/prop.rs
proof-libs/fstar/core/Core.Ops.Arith.fsti
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Folds.fsti
proof-libs/fstar/rust_primitives/Rust_primitives.Hax.fst
test-harness/src/snapshots/toolchain__loops into-fstar.snap
tests/loops/src/lib.rs

This PR adds invariants to `while` loops (using the macro `hax_lib::loop_invariant` that is already used in for loops). It also adds a macro to prove termination (`hax_lib::loop_decreases`), that takes a decreasing `hax_lib::Int` .

Add invariants for while loops.

---

engine/lib/concrete_ident/concrete_ident_view.ml
engine/names/extract/build.rs
engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js
frontend/exporter/src/body.rs
frontend/exporter/src/state.rs
frontend/exporter/src/types/def_id.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/new/full_def.rs
frontend/exporter/src/types/ty.rs
frontend/exporter/src/utils/type_map.rs
test-harness/src/snapshots/toolchain__include-flag into-coq.snap

Promoted constants have their own ad-hoc identifier scheme which is a `(DefId, u32)` pair. They would have a normal `DefId` if not for performance reasons (https://github.com/rust-lang/rust/pull/111693). To simplify Charon's life, this makes hax give a `DefId` to promoted constants, along with a `FullDef` when requested.

Add a fake `DefId` for promoted constants

---

proof-libs/fstar/core/Core.Fmt.fsti

This PR adds a dummy instance of `t_Debug` for `Prims.bool` and for pairs of instances of `t_Debug`.
`core::fmt::Debug` is implemented for a lot of types in `core::fmt`, but I only need some instance for `(Prims.bool & Prims.bool)` in the context of ATLAS, so I felt like this was the most generic way I could get that, which would also be potentially useful for others.

Add Instances of `Core.Fmt.t_Debug` for `Prims.bool` and pairs

---

frontend/exporter/src/constant_utils.rs
frontend/exporter/src/constant_utils/uneval.rs

That's the most common remaining constant-related failure. I still don't know how to translate evaluated constants of function pointer type, will have to poke at const eval some more.

Translate evaluated closure constants

---

hax-lib/macros/src/implementation.rs

A `hax_lib::lemma` typically have no body: only the signature really matters. The proof will be hand written in the target language, or assumed. Also, in proof scripts, we don't necessarily use explicit names to refer to inputs: tactic often deal with whatever binder exists in the environment, while automated proof assistant will pick bindings automatically. Thus, unused inputs in lemmas *body* are perfectly fine.
This commit insert automatic `#[allow(unused_variables)]` where needed.

Silence unused inputs in lemmas

---

engine/backends/fstar/fstar_backend.ml
engine/lib/attr_payloads.ml
hax-lib/build.rs
hax-lib/macros/src/dummy.rs
hax-lib/macros/src/implementation.rs
hax-lib/macros/src/utils.rs
hax-lib/macros/types/src/lib.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR adds support for SMT patterns in lemmas written in Rust.
For example:
```rust
fn dummy_function(x: u32) -> u32 {
x
}
#[hax::lemma]
#[hax::fstar::smt_pat(x)]
fn apply_dummy_function_lemma(x: u32) -> Proof<{ x == dummy_function(x) }> {}
```

feat(hax-lib&backend): F*: support for SMT patterns

---

hax-lib/build.rs
hax-lib/macros/src/dummy.rs
hax-lib/macros/src/implementation.rs
test-harness/src/snapshots/toolchain__attributes into-fstar.snap
tests/attributes/src/lib.rs

This PR adds a `fstar::postprocess_with` macro to be able to use tactics to postprocess an item.
Related to https://github.com/cryspen/libcrux/pull/937

feat(hax_lib/macros): F*: add `postprocess_with`

---

proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti

This function is needed by https://github.com/cryspen/libcrux/pull/865

Add logor_disjoint to Rust_primitives.Integers

---

frontend/exporter/src/constant_utils/uneval.rs
frontend/exporter/src/traits.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/mir.rs
frontend/exporter/src/types/thir.rs
frontend/exporter/src/types/ty.rs

Generic args always include parent arguments (e.g. the args of an impl if we're talking of a method impl, or the args of the enclosing function if we're talking about a closure). This makes it so we also consistently include parent impl exprs.
The second commit it optional, tests pass with or without it, I'm not sure which one you want.

Consistently translate impl exprs for parent items

---

engine/dune-project
engine/hax-engine.opam
engine/hax-engine.opam.template
flake.nix

This pins ocamlgraph in nix, waiting for https://github.com/NixOS/nixpkgs/pull/397883.
Fixes https://github.com/cryspen/hax/issues/1371.
I opened https://github.com/cryspen/hax/issues/1453 to track this pin.

fix(engine/nix): pin ocamlgraph, waiting for https://github.com/NixOS/nixpkgs/pull/397883

---

hax-lib/macros/src/implementation.rs
justfile

Fixes #1448
The previous fix #1436 was not effective in most case, I simplified the logic of the macro `lemma` and fixed the bug.
I tested it on ~`minicore`~ `core-models` on libcrux: now that works.

Fix unused in lemmas

---

engine/lib/concrete_ident/concrete_ident.ml
engine/lib/concrete_ident/concrete_ident_view.ml
engine/lib/concrete_ident/concrete_ident_view_types.ml
tests/Cargo.lock

This adds support for InlineConst in concrete idents. Should fix the following example: https://hax-playground.cryspen.com/#fstar/27ba29ff72/gist=c2fec53eb7833900672a10c116498021

fix(engine) Add InlineConst in concrete_idents.

---

proof-libs/fstar/core/Core.Cmp.fsti

fix(proof-libs) Remove fields that shouldn't be in PartialOrd.

---

docs/manual/index.md
docs/manual/quick_start/index.md
docs/manual/tutorial/data-invariants.md
docs/manual/tutorial/index.md
docs/manual/tutorial/panic-freedom.md
docs/manual/tutorial/properties.md

Documentation occasionally suffers from lines such as `F* does this, F* does that` being rendered as "F *does this, F* does that" (because different Markdown interpreters are differently smart about deciding when a `*` means italics, and then hides the star from output). Example:
> ![Screenshot 2025-06-11 at 11-27-53 Panic freedom - hax](https://github.com/user-attachments/assets/44abe6a4-8e70-4335-84e8-2526562461e1)
This PR goes replaces the `F*` in the Markdown files with `F\*` (as it already was in some places), which renders correctly.

docs: Escape "*" in "F*" from Markdown

---

frontend/exporter/src/traits/resolution.rs
frontend/exporter/src/traits/utils.rs
frontend/exporter/src/types/new/full_def.rs

This translates trait aliases exactly like traits. The difference with trait is that they have a magic blanket impl, which is implicitly referenced with a `ImplExprAtom::BuiltinOrAuto` trait expression.
Generating the impl is left to consumers of the frontend; I tried adding a fake `DefId` like I did for promoted constants, but trait resolution operates on real `DefId`s so it was hard to get it to resolve clauses correctly. In the end it was easier to construct the blanket impl in charon.

full_def: support trait aliases

---

Cargo.lock
rust-engine/Cargo.toml
rust-engine/src/ast.rs
rust-engine/src/lib.rs
rust-engine/src/printer.rs
rust-engine/src/printer/allocator.rs

This commit introduces a [`pretty`](https://docs.rs/pretty/latest/pretty/index.html) allocator indexed by a printer, enabling multiple printers to cohexist and to implement the type `Pretty`.
This solves the following issue. hax has multiple printer and each must implement the trait [`Pretty`](https://docs.rs/pretty/latest/pretty/trait.Pretty.html) for the types of our AST.
We would end up with overlapping implementations instances of the trait `Pretty` for our AST types.
The document allocator introduced by this commit is simply a wrapper with a type index `Printer`.
It contains a box allocator (given by `pretty`) and a printer.
This commit also introduces automatic span annotations, by defining implementations for all types carrying span informations.
In order to let the backend freely …

Rust Engine: allow multiple backends to implement the `Pretty` trait

---

README.md

Fixes a minor typo in `README.md`.

Fix typo: frontent -> frontend

---

Cargo.lock
cli/subcommands/src/cargo_hax.rs
engine/bin/lib.ml
hax-types/src/cli_options/mod.rs
justfile
rust-engine/Cargo.toml
rust-engine/src/ast/identifiers.rs
rust-engine/src/lib.rs
rust-engine/src/main.rs
rust-engine/src/names.rs
rust-engine/src/names/generated.rs

This PR introduce the file `names.rs`, which provides a list of handy `DefId` for the engine.
For example, to be able to resugar `std::ops::Add::add(x, y)` into `x + y`,
we need to:
1. match on the expression `std::ops::Add::add(x, y)`, figure out it is the
application of the function denoted by the global identifier
`std::ops::Add::add` with arguments `x` and `y`.
2. check that global identifier `id: GlobalId` `std::ops::Add::add` is
indeed `std::ops::Add::add`.
Point (2.) seems a bit totological, but we need to write a comparison like
`x == the_function_add`. This module basically provides such
`the_function_add` symbols.
As an example, the names `std::option::Option::Some` and `None` will be provided by this module as:
```rust
mod std {
mod option {
mod Option {
fn Some() -> DefId { …
```

Rust Engine: expose common `DefId`s in the Rust engine

---

.utils/rust-by-example.js
hax-lib/proof-libs/fstar-secret-integers/core/Core.Str.fsti
hax-lib/proof-libs/fstar/core/Alloc.String.fst
hax-lib/proof-libs/fstar/core/Core.F32.fsti
hax-lib/proof-libs/fstar/core/Core.Fmt.fsti
hax-lib/proof-libs/fstar/core/Core.Iter.Traits.Iterator.fst
hax-lib/proof-libs/fstar/core/Core.Mem.fsti
hax-lib/proof-libs/fstar/core/Core.Ops.Arith.fsti
hax-lib/proof-libs/fstar/core/Core.Ops.Drop.fsti
hax-lib/proof-libs/fstar/core/Core.Ops.Function.fsti
hax-lib/proof-libs/fstar/core/Core.Str.Iter.fsti
hax-lib/proof-libs/fstar/core/Core.Str.Traits.fsti
hax-lib/proof-libs/fstar/core/Std.F64.fsti
hax-lib/proof-libs/fstar/core/Std.Io.Stdio.fsti
rustc-coverage-tests/test_config.yaml

This PR extends the `proof-lib/fstar` representation of rust core and primitives to support more of `rust-by-example`.
Out of the 24 sets of examples, 19 work. Proper automated testing of those example is left for a future PR.

Proof lib/fstar support more rbe

---

cli/default.nix

This injects `libiconv` at runtime in the env var `DYLD_LIBRARY_PATH`, fixing `nix run .#` on MacOS.
Thanks to @fjahr that reported the issue and submitted a PR. This PR is very similar, but injects `libiconv` only on the end binary.

fix(nix): make `nix run` work on darwin

---

.github/workflows/mlkem.yml

When a change in hax requires a change in ML-KEM, and vice-versal, we currently just bypass CI.
With this commit, one can now write:
This will make the CI use libcrux at `some-git-ref` instead of `main`.
(note I'm putting a screenshot here, otherwise this will override the version for this PR as well)
libcrux-ref: some-git-ref

feat(ci): mlkem job: use specific libcrux revision

---

hax-lib/proof-libs/fstar/core/Core.Mem.Manually_drop.fsti
hax-lib/proof-libs/fstar/core/Core.Mem.Maybe_uninit.fsti
hax-lib/proof-libs/fstar/core/Core.Mem.Transmutability.fsti
hax-lib/proof-libs/fstar/core/Core.Mem.fsti
hax-lib/proof-libs/fstar/core/Core.Num.Niche_types.fsti
hax-lib/proof-libs/fstar/core/Core.Time.fsti

This PR contains the changes from hax-evit up to June 11th. We add interfaces to the f* proof libs that were extracted using hax from the actual definitions in Rust core.

Upstream changes from evit up to June 11th 2025.

---

.github/workflows/install_and_test.yml
flake.nix

This PR makes the CI run the `examples` test cases outside of the Nix sandbox.
Nix enforce reproducability, thus disable network.
For Lean, @clementblaudeau needs to adds example that have a third party dependency: putting the burden of packaging examples with nix so that they can be in the CI is unpleasant and not useful.
Thus, this PR now uses nix to build the binary dependencies of the examples, but then the examples are run outside of the sandbox.
@clementblaudeau if the PR is green, you can rebase yours onto this one!
EDIT: leaving it as draft, let's wait for CI to be happy

feat(nix/ci): run examples outside of the sandbox

---

Cargo.lock
rust-engine/Cargo.toml

Fixes https://github.com/cryspen/hax/issues/1598.
Thanks @nadrieril, who merged https://github.com/Nadrieril/derive-generic-visitor/pull/2 and published a new version of that crate :)

misc(rengine): stop pinning `derive-generic-visitor` with a git branch

---

justfile
rust-engine/src/printer/pretty_ast.rs

This PR adds a command `show-json` to our `justfile`.
I forgot to commit it.
This PR also makes sure to clean up the temporary file created by `show-json`: whenever we first write to that temp file, we try to drop it.
Thanks @clementblaudeau, who saw the command was missing in the justfile

Rust Engine: improve debug utility `show-json`

---

hax-lib/proof-libs/lean/Lib.lean
rust-engine/src/ast/identifiers.rs
rust-engine/src/backends.rs
rust-engine/src/backends/lean.rs
rust-engine/src/backends/rust.rs
rust-engine/src/main.rs
test-harness/src/snapshots/toolchain__lean-tests into-lean.snap
tests/lean-tests/src/lib.rs

This PR is based on #1603.
It updates the Lean backend to the new printing infrastructure.
#1603 and #1600 added new infrastructure for printing, based on the return of experience of the Lean printer. Specifically, they introduced a proper notion of backend/printer, and some utils for writing `docs`.
This PR updates the Lean backend to the new infrastructure, which unfortunately makes for a monolithic swap. It should not make any semantic changes, besides whitespace and two library edits : 
* integer types are no longer defined as an indirection : `usize` is now `Usize`, `u8` is now `UInt8`, etc
* for clarity, rust arrays and vectors are now defined as an indirection `abbrev RustVector := Array`. The fact that Lean and Rust have opposite terminology was a source of confusion

Update Lean printer to new infrastructure

---

.github/workflows/clippy_rust_engine.yml

This PR makes clippy deny lints in CI.
Our CI job was just emitting warnings, doing nothing in practice.
cc @franziskuskiefer

ci(rengine): clippy: deny lints

---

frontend/exporter/src/types/hir.rs

This PR adds a visibility field to items in the HIR AST.

feat(frontend/hir): add visibility to items

---

rust-engine/src/ast/identifiers/global_id/view.rs

This fixes a bug you had @clementblaudeau.

fix(rengine): missed case `Static` in name rendering

---

CONTRIBUTING.md

After chatting with @karthikbhargavan, @clementblaudeau and @maximebuyse, we decided to change the semantics of the assignee field on this repository.
The assignee of an issue or a PR is the person responsible for the issue or PR. The notion of assignee is thus now decorelated to "this item is being worked on actively by person X".
To everyone: feel free to suggest different wording if you think this is still unclear!

CONTRIBUTING.md: change and clarify the meaning of assignee

---

.gitignore
rustc-coverage-tests/Cargo.toml
rustc-coverage-tests/README.md
rustc-coverage-tests/proofs/lean/extraction/lakefile.toml
rustc-coverage-tests/run-coverage-tests.py
rustc-coverage-tests/snapshots/fstar/Coverage.Attr.Trait_impl_inherit.fst
rustc-coverage-tests/snapshots/fstar/Coverage.Inner_items.fst
rustc-coverage-tests/src/lib.rs
rustc-coverage-tests/test_config.yaml

This PR extends the existing infrastructure to run rustc coverage tests with lean extraction (and type checking). Currently all tests fail type checking, a lot of it seems to be because they return unit and there is a bug with that (should be fixed by https://github.com/cryspen/hax/pull/1629)

Lean backend - Run rustc coverage tests for lean.

---

docs/default.nix
flake.nix

Fixes #1638, `odoc` causes issues which require time to debug. This is a temporary fix to remove the step that builds Ocaml documentation. I opened https://github.com/cryspen/hax/issues/1675 to reactivate later.

Temporarily remove ocaml doc build because of odoc issue.

---

engine/backends/coq/coq/coq_backend.ml
engine/backends/coq/ssprove/ssprove_backend.ml
engine/backends/fstar/fstar_backend.ml
engine/backends/lean/lean_backend.ml
engine/lib/phases/phase_rewrite_local_self.ml
engine/lib/phases/phase_rewrite_local_self.mli

Moves the function `local_self_bound_as_self` out of the F* backend to a proper phase `Rewrite_local_self`. Add `Rewrite_local_self` to the phases of the F*, Lean, Coq and SSProve backends.

fix(engine): add rewrite local self as a proper phase

---

docs/RFCs/.nav.yml
docs/engine/toolchain_structure/index.md

This PR makes minor documentation updates:
- Hide the RFCs tab which has never been used
- Add a page under the engine docs, to describe the toolchain structure

Docs: hide RFCs tab and add toolchain structure page.

---

.gitignore
CHANGELOG.md
docs/manual/faq/include-flags.md
engine/lib/dependencies.ml
hax-lib/macros/src/implementation.rs

We already have the `hax_lib::include` macro but it doesn't have any effect. With this PR, when computing the set of items to extract based on include flag clauses, we force items that have `hax_lib::include` to be always extracted.

Allow hax_lib::include to override -i flags.

---

engine/lib/span.ml

Drive by PR while looking at tests.
The engine had a bug where the IDs of the owner hints were reversed.

fix(engine): fix owner_id

---

CHANGELOG.md
hax-lib/proof-libs/fstar/core/Alloc.Collections.Vec_deque.fsti
hax-lib/proof-libs/fstar/core/Core.Cmp.fsti
hax-lib/proof-libs/fstar/core/Core.Iter.Traits.Iterator.fst

This PR improves the F* proof lib by:
- fixing some `_super` hashes in `core::cmp`
- making the `VecDeque` models slightly less abstract to allow more precise reasoning when using this data structure

Better VecDeque model and other F* proof lib improvements/fixes.
