- Cargo.lock
- Cargo.toml
- cli/driver/Cargo.toml
- cli/driver/src/driver.rs
- cli/subcommands/src/cargo_circus.rs
- tests/.gitignore
- tests/Cargo.toml
- tests/enum-struct-variant/Cargo.toml
- tests/enum-struct-variant/src/lib.rs
We need tests for each part. I started a generic `tests` directory. We might want to split this into frontend/engine tests.
There's also a test case in there that is failing right now.
This should get added to the CI as well.
I also enabled logging to allow debugging.
> start tests

- engine/backends/coq/coq_backend.ml
- engine/backends/easycrypt/easycrypt_backend.ml
- engine/backends/fstar/fstar_backend.ml
- engine/lib/ast.ml
- engine/lib/import_thir.ml
- engine/lib/phases/phase_drop_references.ml
- engine/lib/subtype.ml
- frontend/exporter/src/all.rs
- frontend/exporter/src/items.rs
- frontend/exporter/src/sinto.rs
Add `use` statements (with resolution information). Imports in coq still need some generalization (currently assume imports are in the `Examples` package), and the updated coq library for hacspec needs to be put somewhere.
> Add use statement

- test-harness/src/snapshots/full__mut-ref-functionalization+into-fstar.snap
- tests/Cargo.toml
- tests/mut-ref-functionalization/Cargo.toml
- tests/mut-ref-functionalization/src/lib.rs
> Add testcase for #90

- cli/driver/src/exporter.rs
- cli/subcommands/Cargo.toml
- cli/subcommands/src/pretty_print_diagnostics.rs
- engine/backends/coq/coq_backend.ml
- engine/backends/easycrypt/easycrypt_backend.ml
- engine/backends/fstar/fstar_ast.ml
- engine/backends/fstar/fstar_backend.ml
- engine/bin/dune
- engine/bin/lib.ml
- engine/lib/ast.ml
- engine/lib/ast_utils.ml
- engine/lib/backend.ml
- engine/lib/diagnostics.ml
- engine/lib/dune
- engine/lib/feature_gate.ml
- engine/lib/import_thir.ml
- engine/lib/phase_utils.ml
- engine/lib/phases/phase_cf_into_monads.ml
- engine/lib/phases/phase_direct_and_mut.ml
- engine/lib/phases/phase_drop_references.ml
- engine/lib/phases/phase_functionalize_loops.ml
- engine/lib/phases/phase_local_mutation.ml
- engine/lib/phases/phase_reconstruct_for_loops.ml
- engine/lib/phases/phase_reconstruct_question_marks.ml
- engine/lib/phases/phase_trivialize_assign_lhs.ml
- engine/lib/print_rust.ml
- engine/lib/print_rust.mli
- engine/lib/side_effect_utils.ml
- engine/lib/subtype.ml
> Soft failing

- frontend/diagnostics/src/lib.rs
- rust-issues.md
I started a file to collect syntax and issues.
This is a kitchen sink where everyone can throw things on. We should then pull out issues from there. But an md file is quicker while working on things.
> rust issues md to collect syntax issues

- .docker/Dockerfile
Fixes docker build for M1, as suggested by @geonnave in issue #71.
Thanks @geonnave :)
> Docker filter syscalls (fixes #71)

- .github/workflows/release.yml
- Cargo.toml
- README.md
- cli/driver/src/driver.rs
- cli/driver/src/exporter.rs
- cli/driver/src/linter.rs
- cli/subcommands/src/pretty_print_diagnostics.rs
- engine/default.nix
- engine/lib/ast_utils.ml
- engine/lib/import_thir.ml
- engine/lib/side_effect_utils.ml
- flake.lock
- frontend/diagnostics/src/lib.rs
- frontend/exporter/src/all.rs
- frontend/exporter/src/items.rs
- frontend/exporter/src/lib.rs
- frontend/exporter/src/state.rs
- frontend/lint/src/lib.rs
- rust-toolchain.toml
- tests/Cargo.lock
- tests/Cargo.toml
- tests/literals/Cargo.toml
- tests/literals/src/lib.rs
- tests/string-literal/src/lib.rs
Updating was not too bothering, so that's a bit a relief
> Update to Rust Nightly 2023-06-02 (stable 1.70.0)

- engine/lib/import_thir.ml
This just links issue #161 in the related error message
> Add issue_id for the error for `or` patterns

- cli/driver/src/exporter.rs
- cli/options/engine/src/lib.rs
- engine/lib/ast.ml
- engine/lib/ast_utils.ml
- engine/lib/diagnostics.ml
- engine/lib/import_thir.ml
- engine/lib/print_rust.ml
- engine/lib/span.ml
- engine/lib/span.mli
- engine/utils/phase_debug_webapp/script.js
- frontend/diagnostics/src/lib.rs
- tests/nested-derefs/Cargo.toml
- tests/nested-derefs/src/lib.rs
> Allow arbitrary unions of spans without loosing any information

- cli/driver/src/driver.rs
- cli/options/src/lib.rs
> add `--deps` option

- engine/lib/print_rust.ml
It's nowhere in `Re`'s doc, but it seems like `Re.Str` is a [reimplentation/a copy pase](https://github.com/ocaml/ocaml-re/blob/ddbc60f8e37e85f6b53b55fad1853cc97db93912/lib/str.ml) of OCaml's standard library, which is basically broken.
Using `Re.Str` resulted in... a stack overflow, when matching on big strings...
Using `Re.Pcre`, the issue is now gone.
> Use `Re.Pcre` instead of `Re.Str`

- frontend/exporter/Cargo.toml
- frontend/exporter/src/body.rs
- frontend/exporter/src/constant_utils.rs
- frontend/exporter/src/rustc_utils.rs
- frontend/exporter/src/types/copied.rs
- frontend/exporter/src/types/mir.rs
- frontend/exporter/src/utils.rs
This PR provides a more uniform way of reporting errors in the exporter.
> Rework frontend errors

- engine/lib/phase_utils.ml
- engine/lib/print_rust.ml
- engine/utils/phase_debug_webapp/script.js
This PR fixes #237 
(the source map mechanism was broken, making debugging much more difficult)
> Fix webapp (fixes `rustfmt` retokenizer)

- .github/workflows/test_installs.yml
As suggested by @franziskuskiefer :)
> Make manual workflow dispatch run everything

- engine/lib/concrete_ident/concrete_ident.ml
- engine/lib/dependencies.ml
> Make `-i` clause consider crate name & add logs 

- engine/lib/ast_utils.ml
A cast `x as T` (say `x` is of type `U`) used to be translated `cast x <: T`; now it's translated `cast (x <: U) <: T`
> fix(engine): fstar: add type info. to casts

- engine/default.nix
- engine/lib/dune
- engine/lib/features.ml
- engine/utils/ppx_generate_features/ppx_generate_features.ml
This PR fixes a small bug and adds some functionality in the PPX generating code relative to AST features.
> PPX: Features: misc. improvements

- Cargo.lock
- cli/driver/Cargo.toml
- cli/driver/src/exporter.rs
> feat(cli): help the user to debug missing `hax-engine` binary

- engine/backends/easycrypt/easycrypt_backend.ml
- engine/lib/feature_gate.ml
- engine/lib/phases/phase_direct_and_mut.ml
- engine/lib/phases/phase_drop_references.ml
- engine/lib/phases/phase_local_mutation.ml
- engine/lib/phases/phase_reconstruct_for_loops.ml
- engine/lib/phases/phase_reconstruct_question_marks.ml
- engine/lib/phases/phase_recontruct_for_index_loops.ml
- engine/lib/phases/phase_trivialize_assign_lhs.ml
- engine/lib/subtype.ml
- engine/utils/ppx_generate_features/ppx_generate_features.ml
All reject phases were dropping span information, this PR fixes that.
> Rejection phases: transport & display span information

- engine/lib/dependencies.ml
- examples/chacha20/proofs/fstar/extraction/Chacha20.Hacspec_helper.fst
- examples/chacha20/proofs/fstar/extraction/Chacha20.fst
- examples/limited-order-book/proofs/fstar/extraction/Lob_backend.fst
- examples/sha256/proofs/fstar/extraction/Sha256.fst
- test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
- test-harness/src/snapshots/toolchain__naming into-coq.snap
- test-harness/src/snapshots/toolchain__naming into-fstar.snap
- test-harness/src/snapshots/toolchain__reordering into-coq.snap
- test-harness/src/snapshots/toolchain__reordering into-fstar.snap
- tests/reordering/src/lib.rs
~~Note: CI might fail because of chacha's diff. I will fix that after merging https://github.com/hacspec/hax/pull/333~~ (fixed)
> feat(engine/deps): use a stable sort for reordering definitions

- .gitignore
- proof-libs/fstar/core/Core.Array.Iter.fsti
- proof-libs/fstar/core/Core.Array.fst
- proof-libs/fstar/core/Core.Convert.fst
- proof-libs/fstar/core/Core.Iter.Adapters.Step_by.fst
- proof-libs/fstar/core/Core.Iter.Traits.Collect.fst
- proof-libs/fstar/core/Core.Iter.Traits.Iterator.fst
- proof-libs/fstar/core/Core.Iter.fsti
- proof-libs/fstar/core/Core.Num.Error.fsti
- proof-libs/fstar/core/Core.Num.fsti
- proof-libs/fstar/core/Core.Ops.Arith.Neg.fsti
- proof-libs/fstar/core/Core.Ops.Arith.fsti
- proof-libs/fstar/core/Core.Ops.Control_flow.fst
- proof-libs/fstar/core/Core.Ops.Index.IndexMut.fst
- proof-libs/fstar/core/Core.Ops.Index.fst
- proof-libs/fstar/core/Core.Ops.Range.fsti
- proof-libs/fstar/core/Core.Ops.Try_trait.fst
- proof-libs/fstar/core/Core.Option.fst
- proof-libs/fstar/core/Core.Panicking.fst
- proof-libs/fstar/core/Core.Result.fst
- proof-libs/fstar/core/Core.Slice.fsti
- proof-libs/fstar/core/Core.Str.Converts.fsti
- proof-libs/fstar/core/Core.Str.Error.fsti
- proof-libs/fstar/core/Core.Str.fsti
- proof-libs/fstar/rust_primitives/Rust_primitives.Hax.fst
This PR contains all the edits we (@karthikbhargavan, @xvzcf, and I) did for Kyber.
> corelib: update F* model

- cli/driver/src/exporter.rs
This will emit a warning message when using the EasyCrypt or ProVerif backends, addressing #358.
Hope I found the appropriate place for the warning code!
> Warn on CLI about experimental backends

- .utils/rebuild.sh
Made a small mistake on PR #343, fixing it
> fix(setup.sh): fix `DUNEJOBS` unset warning

- engine/lib/concrete_ident/names.rs
- engine/lib/phases/phase_trivialize_assign_lhs.ml
- proof-libs/fstar/core/Core.Ops.Range.fsti
- proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Monomorphized_update_at.fst
- test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
> Monomorphize update at

- hax-lib/proofs/fstar/extraction/Hax_lib.fst
> Revert "Change definition of hax_lib::implies in Fstar to get lax typechecking working for libcrux Kyber."

- setup.sh
> feat(install): check NodeJS version

- .github/workflows/test.yml
- hax-lib/src/lib.rs
> no std hax lib

- engine/lib/ast.ml
- engine/lib/import_thir.ml
- engine/lib/subtype.ml
- frontend/exporter/src/traits.rs
- test-harness/src/snapshots/toolchain__traits into-fstar.snap
- tests/traits/src/lib.rs
> fix(frontend): fix select_trait_candidate

- engine/default.nix
PR #489 broke documentation extraction, this PR fixes it
> fix(engine/nix): fix engine docs

- engine/lib/ast_utils.ml
- engine/lib/phases/phase_and_mut_defsite.ml
- test-harness/src/snapshots/toolchain__mut-ref-functionalization into-fstar.snap
- tests/mut-ref-functionalization/src/lib.rs
> Allow params of the shape `_: &mut ...`

- cli/options/src/lib.rs
- engine/backends/fstar/fstar_backend.ml
- engine/lib/ast_utils.ml
- engine/lib/dependencies.ml
This PR moves traits and impls to fstis
TODO:
> Fix fstar interfaces

- proof-libs/fstar/rust_primitives/Rust_primitives.Iterators.fsti
This commit adds a precondition to the body of `foldi_chunks_exact` loops. A body takes an index `i` and a sequence `chunk`: the precondition now says that `chunk` is exactly the `i`th chunk of the entire sequence.
This is required for Kyber serialize proofs, and Kyber/extraction-edited still TC with this patch.
> feat(proof-libs/fstar): add `update-foldi_chunks_exact`

- proof-libs/fstar/rust_primitives/Rust_primitives.BitVectors.fsti
This commit changes the representation of bit vectors from partial maps to partial maps with functional extensibility.
This allows us to assert the equality of two bit-vectors when they are bit-wise equal.
> feat(proof-libs/fstar): bit vec: use funext

- engine/backends/coq/coq/coq_backend.ml
- engine/backends/easycrypt/easycrypt_backend.ml
- engine/backends/fstar/fstar_backend.ml
- engine/backends/proverif/proverif_backend.ml
- engine/lib/ast.ml
- engine/lib/ast_utils.ml
- engine/lib/ast_visitors.ml
- engine/lib/diagnostics.ml
- engine/lib/features.ml
- engine/lib/phases.ml
- engine/lib/phases/phase_functionalize_loops.ml
- engine/lib/phases/phase_functionalize_loops.mli
- engine/lib/phases/phase_reconstruct_while_loops.ml
- engine/lib/phases/phase_reconstruct_while_loops.mli
- engine/lib/print_rust.ml
- engine/lib/side_effect_utils.ml
- engine/lib/subtype.ml
- engine/names/src/lib.rs
- proof-libs/fstar/rust_primitives/Rust_primitives.fst
- test-harness/src/snapshots/toolchain__loops into-fstar.snap
- tests/loops/Cargo.toml
- tests/loops/src/lib.rs
(under an hour!)
Fixes https://github.com/hacspec/hax/issues/522
> feat(engine): add while loops

- README.md
Zulip provides us as an open source project with a free cloud standard tier. This adds an acknowledgement for that in the readme.
> Acknowledge Zulip support

- frontend/exporter/src/constant_utils.rs
In MIR, some specific bytestr cases for constants were not handled by the frontend (see #578).
This PR fixes that. I cannot add tests to the repo though, this path is never used in hax.
> fix(exporter/mir): handle `GlobalAlloc::Memory` case

- engine/backends/proverif/proverif_backend.ml
> Avoid gratuitous definition / emission of events

- engine/backends/fstar/fstar_backend.ml
Write a comprehensible error message, and link to https://github.com/hacspec/hax/issues/464
> fix(engine/f*): better error for #464

- proof-libs/fstar/core/Core.Core_arch.X86.fsti
- proof-libs/fstar/core/Core.Core_arch.fsti
- proof-libs/fstar/core/Core.fst
We need some core types. Am I doing this right?
> add F* core arch type

- engine/lib/import_thir.ml
- test-harness/src/snapshots/toolchain__literals into-coq.snap
- test-harness/src/snapshots/toolchain__literals into-fstar.snap
- tests/literals/src/lib.rs
> feat(engine): allow cast of closures as fn pointers

- README.md
This is following PRs
https://github.com/hacspec/hacspec.github.io/pull/1 and https://github.com/hacspec/hacspec.github.io/pull/2.
> feat(readme): reflect changes from hascpec.github.io

- frontend/exporter/src/types/copied.rs
- frontend/exporter/src/types/todo.rs
This translates some missing information about `dyn Trait`.
> Translate `dyn Trait` information

- cli/driver/src/features.rs
> Add nicer error messages when rustc emits an error in detect_forking.

- cli/subcommands/src/cargo_hax.rs
- hax-types/src/cli_options.rs
> feat(frontend): Add option to control output directory

- proof-libs/fstar/rust_primitives/Rust_primitives.BitVectors.fst
- proof-libs/fstar/rust_primitives/Rust_primitives.BitVectors.fsti
@karthikbhargavan  we need that one as well for MLKEM
> bit_vec_to_int_t

- proof-libs/fstar/core/Alloc.Borrow.fst
- proof-libs/fstar/core/Alloc.Borrow.fsti
- proof-libs/fstar/core/Alloc.Boxed.fst
- proof-libs/fstar/core/Core.Fmt.fsti
- proof-libs/fstar/core/Core.Marker.fst
- proof-libs/fstar/core/Std.Hash.Random.fsti
Added rust core types for use by sandwich.
> Add Rust Core Fstar Definitions.

- engine/lib/ast_utils.ml
> doc: disambiguate_local_idents

- engine/lib/import_thir.ml
This addresses partially #921: instead of having a fallback, I'm trying to attach an issue to every single failure thrown by the engine.
This PR adds issues IDs for every error of the THIR import phase.
> chore: assign an issue for every error in `import_thir`

- engine/lib/phases/phase_cf_into_monads.ml
Issue #96 was closed in favor of #15, this commit reflects that in code.
> fix(engine): change issue id

- CONTRIBUTING.md
I stole most of https://github.com/openmls/openmls/blob/main/CONTRIBUTING.md, removed some things, and added some others.
> feat(doc): add `CONTRIBUTING.md`

- engine/DEV.md
> fix: DEV.md debug engine

- .utils/rebuild.sh
- justfile
Thanks @maximebuyse for noticing that bug!
> fix: justfile

- frontend/exporter/src/rustc_utils.rs
> fix(frontend): this was reverted by mistake

- engine/lib/concrete_ident/concrete_ident.ml
- engine/lib/concrete_ident/concrete_ident.mli
- engine/lib/dependencies.ml
- test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap
- tests/cyclic-modules/src/lib.rs
> fix(engine) Move variant constructors in recursive bundling.

- engine/lib/dependencies.ml
- test-harness/src/snapshots/toolchain__cyclic-modules into-fstar.snap
- tests/Cargo.lock
- tests/cyclic-modules/Cargo.toml
- tests/cyclic-modules/src/lib.rs
> fix(engine) Keep late_skip attributes in bundles

- .github/workflows/bertie.yml
This adds CI jobs for running fstar extraction on some important crates that use hax.
> Cryspen green.

- frontend/exporter/src/traits/resolution.rs
- frontend/exporter/src/types/hir.rs
- frontend/exporter/src/types/mir.rs
- frontend/exporter/src/types/new/full_def.rs
- frontend/exporter/src/types/ty.rs
- test-harness/src/snapshots/toolchain__traits into-fstar.snap
A series of improvements, including better support for struct/variant constructor functions.
> Various tweaks

- hax-lib/src/dummy.rs
- proof-libs/fstar/core/Core.Array.fsti
- proof-libs/fstar/core/Core.Num.fsti
This PR collects a set of library extensions and additions needed for the first round of PRs on ML-DSA.
> Library additions for ML-DSA verification

- frontend/exporter/src/types/new/full_def.rs
Charon now normalizes associated types by itself so we don't need to do it in hax. This is good because this normalization caused some loss of important lifetime information.
> full_def: no need to normalize clauses eagerly anymore

- proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti
These facts are needed by https://github.com/cryspen/libcrux/pull/796
> Add more facts to logand_lemma

- engine/backends/fstar/fstar_backend.ml
- engine/lib/phases/phase_specialize.ml
- engine/names/src/lib.rs
- test-harness/src/snapshots/toolchain__traits into-fstar.snap
- tests/Cargo.lock
- tests/traits/src/lib.rs
> fix(engine) Allow implementing arithmetic traits.

- proof-libs/fstar/core/Core.Ops.Bit.fsti
> F* typeclass for `core::ops::BitXor`

- proof-libs/fstar/core/Core.Num.fsti
- proof-libs/fstar/core/Rand.Distr.Distribution.fsti
- proof-libs/fstar/core/Rand.Distr.Integer.fsti
> Bertie libs

- frontend/exporter/src/types/mir.rs
It doesn't feel like Hax's responsibility: it should translate the MIR as agnostically as possible.
> Hax shouldn't distinguish the `If` case in MIR

- frontend/exporter/src/traits/resolution.rs
There exist built-in associated types that don't have a definition other than the associated type alias itself, such as [`Pointee::Metadata`](https://doc.rust-lang.org/std/ptr/trait.Pointee.html) and [`DiscriminantKind::Discriminant`](https://doc.rust-lang.org/std/marker/trait.DiscriminantKind.html).
This PR removes an error message that was triggered by attempting to find a value for these associated types. Leaving them unnormalized is actually the correct thing to do.
> Don't error on built-in associated types

- proof-libs/fstar/core/Core.Core_arch.Arm_shared.Neon.fsti
- proof-libs/fstar/core/Core.Core_arch.X86.fsti
This PR adds declarations for all the SIMD types we may refer to.
> simd types

- engine/default.nix
- engine/hax-engine.opam
- engine/hax-engine.opam.template
- engine/lib/dependencies.ml
- engine/lib/graph_stable_sort.ml
> Stop depending on ocamlgraph fork.

- docs/blog/posts/this-month-in-hax/2025-03.md
Fixes https://github.com/cryspen/home/issues/263
> feat(docs/blog): this month in hax 03 2025

- frontend/exporter/src/types/new/full_def.rs
This helper makes it possible to resolve a path like `std::clone::Clone::clone_from` into a `DefId` by recursively looking through an item's children until we find the item we want. I based this on [`clippy_utils::def_path_res_with_base`](https://doc.rust-lang.org/stable/nightly-rustc/clippy_utils/fn.def_path_res_with_base.html) which does exactly that.
> full_def: Add helper to explore an item's children

- proof-libs/fstar/rust_primitives/Rust_primitives.Hax.Folds.fsti
> Fix range loops for empty ranges.

- frontend/exporter/src/types/mir.rs
This line: https://github.com/cryspen/hax/blob/40961957dba9f338dcf89ee9272062b5c7657eb1/frontend/exporter/src/types/mir.rs#L847 is incorrect. Turns out we don't need to recompute place types ourselves, rustc provides APIs for that. This PR uses that API to simplify place translation.
> Simplify MIR place translation

- .github/workflows/charon.yml
This PR just makes it possible to trigger manually from the *Action* tab the Charon job.
> Update charon.yml: add `workflow_dispatch`

- engine/lib/dependencies.ml
> fix(engine) Export traits defined in bundles.

- engine/lib/import_thir.ml
We were missing a few borrows when converting binary operators to function calls. This used to be unimportant as all of our backends used to drop borrows. However, now, with the Rust printer, we want to output valid Rust, thus such borrows are relevant.
> feat(engine): import thir: add missing borrows
